2024-07-11 12:55:10.028102: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2024-07-11 12:55:10.028287: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2024-07-11 12:55:19,020 | app.py:165 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2024-07-11 12:55:19,120 | app.py:179 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2024-07-11 12:55:19,121 | server.py:89 | Initializing global parameters
INFO flwr 2024-07-11 12:55:19,121 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2024-07-11 12:55:20,567 | server.py:280 | Received initial parameters from one random client
INFO flwr 2024-07-11 12:55:20,567 | server.py:91 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:20,583 | server.py:98 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.43666666666666665}
INFO flwr 2024-07-11 12:55:20,583 | server.py:104 | FL starting
DEBUG flwr 2024-07-11 12:55:20,851 | server.py:227 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:20,897 | server.py:241 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2024-07-11 12:55:20,900 | fedavgm.py:198 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:20,909 | server.py:131 | fit progress: (1, 0.3987918454799455, {'accuracy': 0.8166666666666667}, 0.3247529)
DEBUG flwr 2024-07-11 12:55:20,909 | server.py:178 | evaluate_round 1: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:20,960 | server.py:192 | evaluate_round 1 received 4 results and 0 failures
WARNING flwr 2024-07-11 12:55:20,960 | fedavg.py:273 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2024-07-11 12:55:20,961 | server.py:227 | fit_round 2: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,010 | server.py:241 | fit_round 2 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,021 | server.py:131 | fit progress: (2, 0.39877130029003466, {'accuracy': 0.81}, 0.43685810000000025)
DEBUG flwr 2024-07-11 12:55:21,022 | server.py:178 | evaluate_round 2: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,048 | server.py:192 | evaluate_round 2 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:21,048 | server.py:227 | fit_round 3: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,086 | server.py:241 | fit_round 3 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,101 | server.py:131 | fit progress: (3, 0.398764012668492, {'accuracy': 0.81}, 0.5173266000000005)
DEBUG flwr 2024-07-11 12:55:21,102 | server.py:178 | evaluate_round 3: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,146 | server.py:192 | evaluate_round 3 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:21,146 | server.py:227 | fit_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,189 | server.py:241 | fit_round 4 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,201 | server.py:131 | fit progress: (4, 0.3987645190563561, {'accuracy': 0.81}, 0.6172947999999998)
DEBUG flwr 2024-07-11 12:55:21,202 | server.py:178 | evaluate_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,238 | server.py:192 | evaluate_round 4 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:21,238 | server.py:227 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,334 | server.py:241 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,346 | server.py:131 | fit progress: (5, 0.39876223053782917, {'accuracy': 0.81}, 0.7621075000000008)
DEBUG flwr 2024-07-11 12:55:21,346 | server.py:178 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,402 | server.py:192 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:21,402 | server.py:227 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,459 | server.py:241 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,472 | server.py:131 | fit progress: (6, 0.39876326624291625, {'accuracy': 0.81}, 0.8878532999999997)
DEBUG flwr 2024-07-11 12:55:21,473 | server.py:178 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,508 | server.py:192 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:21,508 | server.py:227 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,561 | server.py:241 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,575 | server.py:131 | fit progress: (7, 0.39876273585429073, {'accuracy': 0.81}, 0.9908602999999996)
DEBUG flwr 2024-07-11 12:55:21,575 | server.py:178 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:21,605 | server.py:192 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:21,606 | server.py:227 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:21,662 | server.py:241 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,675 | server.py:131 | fit progress: (8, 0.3990247105618117, {'accuracy': 0.8166666666666667}, 1.0905105000000006)
DEBUG flwr 2024-07-11 12:55:21,675 | server.py:178 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:21,711 | server.py:192 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:55:21,711 | server.py:227 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:21,773 | server.py:241 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,785 | server.py:131 | fit progress: (9, 0.3990313004617525, {'accuracy': 0.8166666666666667}, 1.201606)
DEBUG flwr 2024-07-11 12:55:21,786 | server.py:178 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:21,823 | server.py:192 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:55:21,823 | server.py:227 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:21,879 | server.py:241 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:21,892 | server.py:131 | fit progress: (10, 0.39903137350689455, {'accuracy': 0.8166666666666667}, 1.3074653999999999)
DEBUG flwr 2024-07-11 12:55:21,892 | server.py:178 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:21,929 | server.py:192 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2024-07-11 12:55:21,930 | server.py:153 | FL finished in 1.3454365999999993
INFO flwr 2024-07-11 12:55:21,930 | app.py:225 | app_fit: losses_distributed [(1, 0.41251688450574875), (2, 0.4158706111567361), (3, 0.41587026559171225), (4, 0.41587012722378686), (5, 0.4158700413647152), (6, 0.41587006194250925), (7, 0.4158700527179809), (8, 0.4176741480827332), (9, 0.4176744465317045), (10, 0.4176744490861893)]
INFO flwr 2024-07-11 12:55:21,930 | app.py:226 | app_fit: metrics_distributed_fit {}
INFO flwr 2024-07-11 12:55:21,930 | app.py:227 | app_fit: metrics_distributed {}
INFO flwr 2024-07-11 12:55:21,931 | app.py:228 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.3987918454799455), (2, 0.39877130029003466), (3, 0.398764012668492), (4, 0.3987645190563561), (5, 0.39876223053782917), (6, 0.39876326624291625), (7, 0.39876273585429073), (8, 0.3990247105618117), (9, 0.3990313004617525), (10, 0.39903137350689455)]
INFO flwr 2024-07-11 12:55:21,931 | app.py:229 | app_fit: metrics_centralized {'accuracy': [(0, 0.43666666666666665), (1, 0.8166666666666667), (2, 0.81), (3, 0.81), (4, 0.81), (5, 0.81), (6, 0.81), (7, 0.81), (8, 0.8166666666666667), (9, 0.8166666666666667), (10, 0.8166666666666667)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.16298109,  0.89795326,  0.72491847,  0.37997584,  0.18443334,
         0.23394391, -0.04177259,  0.03904608]]), array([0.16985273])]
[array([[-2.01048188,  0.88480321,  0.71903859,  0.36772209,  0.1383174 ,
         0.12510158,  0.01737283,  0.03810306]]), array([0.18521176])]
[array([[-2.01069996,  0.88476941,  0.71915388,  0.36780237,  0.13835008,
         0.12506796,  0.01750279,  0.03814599]]), array([0.18476826])]
[array([[-2.01088432,  0.88482375,  0.71918673,  0.36781323,  0.13837309,
         0.12507056,  0.01744283,  0.03815862]]), array([0.18502382])]
[array([[-2.01089069,  0.88485395,  0.7192394 ,  0.36787232,  0.13831035,
         0.12503649,  0.01747486,  0.03811863]]), array([0.1849459])]
[array([[-2.01089443,  0.88484368,  0.71921755,  0.36784676,  0.13834128,
         0.12505413,  0.01745702,  0.03813895]]), array([0.18498025])]
[array([[-2.0108939 ,  0.88484973,  0.71922992,  0.3678603 ,  0.13832556,
         0.12504535,  0.01746579,  0.03812857]]), array([0.18496261])]
[array([[-1.95053843,  0.93271043,  0.74725959,  0.39966293,  0.15572909,
         0.13419371, -0.01384702,  0.0183058 ]]), array([0.00649905])]
[array([[-1.95012399,  0.93260917,  0.74717101,  0.39959444,  0.15567424,
         0.13417844, -0.01395099,  0.01825756]]), array([0.00662712])]
[array([[-1.95011908,  0.93260696,  0.74716968,  0.39959466,  0.1556739 ,
         0.13417745, -0.01395102,  0.01825909]]), array([0.00662395])]
>>>>>>>>>>>>>run time:
0.609375s
