2023-09-18 18:07:33.289671: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:07:33.289853: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:07:40,854 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:07:40,912 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:07:40,913 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:07:40,913 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:07:41,910 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:07:41,910 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:41,926 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.43666666666666665}
INFO flwr 2023-09-18 18:07:41,926 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:07:42,108 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:42,133 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:07:42,136 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,145 | server.py:125 | fit progress: (1, 0.4010108722712852, {'accuracy': 0.8133333333333334}, 0.21945230000000038)
DEBUG flwr 2023-09-18 18:07:42,146 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:42,170 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:07:42,170 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:07:42,170 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:42,190 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,200 | server.py:125 | fit progress: (2, 0.39914518115413894, {'accuracy': 0.81}, 0.2733605000000008)
DEBUG flwr 2023-09-18 18:07:42,200 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:42,216 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:07:42,216 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:42,235 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,245 | server.py:125 | fit progress: (3, 0.3991550169947403, {'accuracy': 0.81}, 0.31835570000000146)
DEBUG flwr 2023-09-18 18:07:42,245 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:42,260 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:07:42,260 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:42,279 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,289 | server.py:125 | fit progress: (4, 0.3991538043533791, {'accuracy': 0.81}, 0.362585300000001)
DEBUG flwr 2023-09-18 18:07:42,289 | server.py:173 | evaluate_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:42,306 | server.py:187 | evaluate_round 4 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:07:42,306 | server.py:223 | fit_round 5: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 18:07:42,335 | server.py:237 | fit_round 5 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,345 | server.py:125 | fit progress: (5, 0.3993301335786789, {'accuracy': 0.81}, 0.41860350000000146)
DEBUG flwr 2023-09-18 18:07:42,346 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:42,373 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:07:42,373 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:42,401 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,413 | server.py:125 | fit progress: (6, 0.39876810967555726, {'accuracy': 0.81}, 0.4867566000000014)
DEBUG flwr 2023-09-18 18:07:42,413 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:42,438 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:07:42,439 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:42,474 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,489 | server.py:125 | fit progress: (7, 0.39876210589761146, {'accuracy': 0.81}, 0.5621078000000015)
DEBUG flwr 2023-09-18 18:07:42,489 | server.py:173 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:42,513 | server.py:187 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:07:42,514 | server.py:223 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:42,545 | server.py:237 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,556 | server.py:125 | fit progress: (8, 0.3987634004566681, {'accuracy': 0.81}, 0.6293066000000014)
DEBUG flwr 2023-09-18 18:07:42,556 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:42,587 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:07:42,587 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:42,622 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,635 | server.py:125 | fit progress: (9, 0.39902459561390824, {'accuracy': 0.8166666666666667}, 0.7092119000000014)
DEBUG flwr 2023-09-18 18:07:42,636 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:42,661 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:07:42,661 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:42,694 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:42,706 | server.py:125 | fit progress: (10, 0.3990312990255144, {'accuracy': 0.8166666666666667}, 0.7795125000000009)
DEBUG flwr 2023-09-18 18:07:42,706 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:42,728 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:07:42,729 | server.py:147 | FL finished in 0.8020983000000008
INFO flwr 2023-09-18 18:07:42,729 | app.py:218 | app_fit: losses_distributed [(1, 0.42193507589399815), (2, 0.4217215199023485), (3, 0.4217225927859545), (4, 0.4217225965112448), (5, 0.416431127559571), (6, 0.4158708914404824), (7, 0.41587003001144957), (8, 0.4183837767158236), (9, 0.4176741374390466), (10, 0.4176744465317045)]
INFO flwr 2023-09-18 18:07:42,729 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:07:42,729 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:07:42,729 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.4010108722712852), (2, 0.39914518115413894), (3, 0.3991550169947403), (4, 0.3991538043533791), (5, 0.3993301335786789), (6, 0.39876810967555726), (7, 0.39876210589761146), (8, 0.3987634004566681), (9, 0.39902459561390824), (10, 0.3990312990255144)]
INFO flwr 2023-09-18 18:07:42,729 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.43666666666666665), (1, 0.8133333333333334), (2, 0.81), (3, 0.81), (4, 0.81), (5, 0.81), (6, 0.81), (7, 0.81), (8, 0.81), (9, 0.8166666666666667), (10, 0.8166666666666667)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.00217267,  0.83683476,  0.75954111,  0.32418463,  0.11636483,
         0.20949715,  0.01197022,  0.11513837]]), array([0.04789376])]
[array([[-2.01865878,  0.84907722,  0.74713215,  0.32718263,  0.10549373,
         0.18839687,  0.00560213,  0.07984675]]), array([0.11539282])]
[array([[-2.0189084 ,  0.84851745,  0.746975  ,  0.3269321 ,  0.10573816,
         0.18758896,  0.00585323,  0.08017093]]), array([0.11707558])]
[array([[-2.01887792,  0.84854543,  0.74699565,  0.3268615 ,  0.10573995,
         0.18754775,  0.00588925,  0.08011439]]), array([0.11713238])]
[array([[-1.95257338,  0.87601983,  0.67789933,  0.39446135,  0.10197918,
         0.14597268,  0.02835053,  0.07111939]]), array([0.07076186])]
[array([[-2.01020678,  0.88468212,  0.71870758,  0.36781414,  0.1383525 ,
         0.12474894,  0.01725045,  0.0379992 ]]), array([0.18562785])]
[array([[-2.01088782,  0.88485247,  0.71924036,  0.36787531,  0.13830711,
         0.12503174,  0.01747917,  0.03811767]]), array([0.18493863])]
[array([[-2.01089413,  0.88484191,  0.71921415,  0.36784323,  0.13834514,
         0.12505624,  0.01745497,  0.03814145]]), array([0.18498486])]
[array([[-1.95053786,  0.93271234,  0.74726369,  0.39966761,  0.15572361,
         0.13419049, -0.01384386,  0.01830223]]), array([0.00649277])]
[array([[-1.950124  ,  0.93260918,  0.747171  ,  0.39959439,  0.15567423,
         0.13417837, -0.01395095,  0.01825752]]), array([0.00662726])]
>>>>>>>>>>>>>run time:
0.421875s
