2023-09-18 18:07:21.112528: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:07:21.112713: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:07:28,652 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:07:28,716 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:07:28,717 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:07:28,717 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:07:29,627 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:07:29,627 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:29,642 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.39666666666666667}
INFO flwr 2023-09-18 18:07:29,643 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:07:29,877 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:29,899 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:07:29,901 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:29,907 | server.py:125 | fit progress: (1, 0.39136646412872317, {'accuracy': 0.8}, 0.2654777999999993)
DEBUG flwr 2023-09-18 18:07:29,908 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:29,930 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:07:29,930 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:07:29,930 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:29,949 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:29,959 | server.py:125 | fit progress: (2, 0.39211681716147906, {'accuracy': 0.81}, 0.3167145999999992)
DEBUG flwr 2023-09-18 18:07:29,959 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:29,976 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:07:29,976 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:29,993 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:30,003 | server.py:125 | fit progress: (3, 0.39211899218714297, {'accuracy': 0.81}, 0.36122879999999924)
DEBUG flwr 2023-09-18 18:07:30,004 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:30,026 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:07:30,027 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:07:30,046 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:30,056 | server.py:125 | fit progress: (4, 0.39211906581108574, {'accuracy': 0.81}, 0.4136337000000001)
DEBUG flwr 2023-09-18 18:07:30,056 | server.py:173 | evaluate_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 18:07:30,077 | server.py:187 | evaluate_round 4 received 4 results and 0 failures
DEBUG flwr 2023-09-18 18:07:30,077 | server.py:223 | fit_round 5: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 18:07:30,104 | server.py:237 | fit_round 5 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:30,114 | server.py:125 | fit progress: (5, 0.3919843356144584, {'accuracy': 0.8}, 0.47141399999999933)
DEBUG flwr 2023-09-18 18:07:30,114 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:30,143 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:07:30,143 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:30,171 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:30,182 | server.py:125 | fit progress: (6, 0.3936472890226386, {'accuracy': 0.8033333333333333}, 0.5399244000000003)
DEBUG flwr 2023-09-18 18:07:30,182 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:30,205 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:07:30,206 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:30,236 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:30,247 | server.py:125 | fit progress: (7, 0.39364414409869414, {'accuracy': 0.8033333333333333}, 0.6050456999999998)
DEBUG flwr 2023-09-18 18:07:30,248 | server.py:173 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:30,268 | server.py:187 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:07:30,269 | server.py:223 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:07:30,298 | server.py:237 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:30,309 | server.py:125 | fit progress: (8, 0.3936450391458044, {'accuracy': 0.8033333333333333}, 0.6665361999999995)
DEBUG flwr 2023-09-18 18:07:30,309 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:30,334 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:07:30,335 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:30,376 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:30,388 | server.py:125 | fit progress: (9, 0.39201307062775187, {'accuracy': 0.8066666666666666}, 0.7458942000000004)
DEBUG flwr 2023-09-18 18:07:30,388 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:30,419 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:07:30,419 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:30,453 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:07:30,466 | server.py:125 | fit progress: (10, 0.3920201620919931, {'accuracy': 0.8066666666666666}, 0.8240175999999995)
DEBUG flwr 2023-09-18 18:07:30,466 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:07:30,491 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:07:30,492 | server.py:147 | FL finished in 0.8493621999999998
INFO flwr 2023-09-18 18:07:30,492 | app.py:218 | app_fit: losses_distributed [(1, 0.39486186392605305), (2, 0.39334152080118656), (3, 0.3933422211557627), (4, 0.40175519032137735), (5, 0.40411200196970076), (6, 0.403387440102441), (7, 0.4033845847561246), (8, 0.40691963391644614), (9, 0.4065522675003324), (10, 0.40655333484922135)]
INFO flwr 2023-09-18 18:07:30,492 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:07:30,492 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:07:30,492 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.39136646412872317), (2, 0.39211681716147906), (3, 0.39211899218714297), (4, 0.39211906581108574), (5, 0.3919843356144584), (6, 0.3936472890226386), (7, 0.39364414409869414), (8, 0.3936450391458044), (9, 0.39201307062775187), (10, 0.3920201620919931)]
INFO flwr 2023-09-18 18:07:30,492 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.39666666666666667), (1, 0.8), (2, 0.81), (3, 0.81), (4, 0.81), (5, 0.8), (6, 0.8033333333333333), (7, 0.8033333333333333), (8, 0.8033333333333333), (9, 0.8066666666666666), (10, 0.8066666666666666)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.0996612 ,  0.96373856,  0.71296191,  0.4023511 ,  0.20552414,
        -0.01111928,  0.03633247, -0.13627745]]), array([0.49174085])]
[array([[-2.03061576,  0.98425906,  0.76061625,  0.34626643,  0.25494102,
         0.0098756 ,  0.00698818, -0.02139523]]), array([0.24066445])]
[array([[-2.0303623 ,  0.98412501,  0.76053822,  0.34623056,  0.2550012 ,
         0.00992538,  0.0069312 , -0.02136712]]), array([0.24043534])]
[array([[-2.03033345,  0.98412042,  0.76054742,  0.34624188,  0.25500939,
         0.00994736,  0.00693159, -0.0213622 ]]), array([0.24034514])]
[array([[-2.03450597,  0.9599515 ,  0.73278522,  0.37598934,  0.1867456 ,
         0.05590893, -0.05132144,  0.01388431]]), array([0.22914189])]
[array([[-1.97496958,  1.01384982,  0.77916978,  0.38368613,  0.19173462,
         0.07012917, -0.02700552, -0.02832629]]), array([0.08059734])]
[array([[-1.97662664,  1.01500891,  0.78025005,  0.38397556,  0.19183318,
         0.07030601, -0.0267051 , -0.02858639]]), array([0.07969189])]
[array([[-1.97645825,  1.01492162,  0.78018747,  0.3839258 ,  0.19180168,
         0.07029794, -0.02669447, -0.02859703]]), array([0.0797479])]
[array([[-1.99079103,  0.98021159,  0.80058048,  0.38233333,  0.17005754,
         0.1025759 , -0.02393239, -0.00717979]]), array([0.11749108])]
[array([[-1.98974572,  0.97953939,  0.80029589,  0.38217863,  0.16964838,
         0.10277873, -0.02436288, -0.00682925]]), array([0.11780661])]
>>>>>>>>>>>>>run time:
0.375s
