2024-07-11 12:54:57.242432: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2024-07-11 12:54:57.242683: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2024-07-11 12:55:06,030 | app.py:165 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2024-07-11 12:55:06,120 | app.py:179 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2024-07-11 12:55:06,120 | server.py:89 | Initializing global parameters
INFO flwr 2024-07-11 12:55:06,120 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2024-07-11 12:55:07,384 | server.py:280 | Received initial parameters from one random client
INFO flwr 2024-07-11 12:55:07,384 | server.py:91 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:07,400 | server.py:98 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.39666666666666667}
INFO flwr 2024-07-11 12:55:07,400 | server.py:104 | FL starting
DEBUG flwr 2024-07-11 12:55:07,642 | server.py:227 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:07,674 | server.py:241 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2024-07-11 12:55:07,676 | fedavgm.py:198 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:07,684 | server.py:131 | fit progress: (1, 0.39714306305399655, {'accuracy': 0.8}, 0.2835573)
DEBUG flwr 2024-07-11 12:55:07,684 | server.py:178 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:07,707 | server.py:192 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2024-07-11 12:55:07,707 | fedavg.py:273 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2024-07-11 12:55:07,707 | server.py:227 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:07,739 | server.py:241 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:07,749 | server.py:131 | fit progress: (2, 0.39527291343804777, {'accuracy': 0.8066666666666666}, 0.3495185000000003)
DEBUG flwr 2024-07-11 12:55:07,749 | server.py:178 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:07,772 | server.py:192 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:55:07,773 | server.py:227 | fit_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:07,801 | server.py:241 | fit_round 3 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:07,813 | server.py:131 | fit progress: (3, 0.39508276185041835, {'accuracy': 0.8033333333333333}, 0.41329439999999984)
DEBUG flwr 2024-07-11 12:55:07,813 | server.py:178 | evaluate_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:07,843 | server.py:192 | evaluate_round 3 received 4 results and 0 failures
DEBUG flwr 2024-07-11 12:55:07,844 | server.py:227 | fit_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:07,877 | server.py:241 | fit_round 4 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:07,890 | server.py:131 | fit progress: (4, 0.3950897001134056, {'accuracy': 0.8033333333333333}, 0.4898623000000004)
DEBUG flwr 2024-07-11 12:55:07,890 | server.py:178 | evaluate_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:07,915 | server.py:192 | evaluate_round 4 received 4 results and 0 failures
DEBUG flwr 2024-07-11 12:55:07,915 | server.py:227 | fit_round 5: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:07,954 | server.py:241 | fit_round 5 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:07,966 | server.py:131 | fit progress: (5, 0.39508927921850634, {'accuracy': 0.8033333333333333}, 0.5654534000000009)
DEBUG flwr 2024-07-11 12:55:07,966 | server.py:178 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:07,999 | server.py:192 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:08,000 | server.py:227 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:08,047 | server.py:241 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:08,061 | server.py:131 | fit progress: (6, 0.3936535320244063, {'accuracy': 0.8033333333333333}, 0.6613369000000002)
DEBUG flwr 2024-07-11 12:55:08,061 | server.py:178 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:08,089 | server.py:192 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:08,089 | server.py:227 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:08,145 | server.py:241 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:08,157 | server.py:131 | fit progress: (7, 0.3936436977831454, {'accuracy': 0.8033333333333333}, 0.7571718000000001)
DEBUG flwr 2024-07-11 12:55:08,158 | server.py:178 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:08,189 | server.py:192 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:08,189 | server.py:227 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:08,236 | server.py:241 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:08,248 | server.py:131 | fit progress: (8, 0.39201319309611876, {'accuracy': 0.8066666666666666}, 0.8489689000000009)
DEBUG flwr 2024-07-11 12:55:08,249 | server.py:178 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:08,298 | server.py:192 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:55:08,299 | server.py:227 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:08,353 | server.py:241 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:08,365 | server.py:131 | fit progress: (9, 0.392020164111833, {'accuracy': 0.8066666666666666}, 0.965041900000001)
DEBUG flwr 2024-07-11 12:55:08,365 | server.py:178 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:08,397 | server.py:192 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:55:08,398 | server.py:227 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:08,450 | server.py:241 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:08,462 | server.py:131 | fit progress: (10, 0.39201942691876024, {'accuracy': 0.8066666666666666}, 1.062702400000001)
DEBUG flwr 2024-07-11 12:55:08,462 | server.py:178 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:08,500 | server.py:192 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2024-07-11 12:55:08,500 | server.py:153 | FL finished in 1.1007756999999998
INFO flwr 2024-07-11 12:55:08,501 | app.py:225 | app_fit: losses_distributed [(1, 0.4015533005197843), (2, 0.40084176510572433), (3, 0.399909837047259), (4, 0.3999134669701258), (5, 0.40402804457006003), (6, 0.40338832281884696), (7, 0.40338446980430964), (8, 0.40655228921345304), (9, 0.40655333995819093), (10, 0.4065534093550273)]
INFO flwr 2024-07-11 12:55:08,501 | app.py:226 | app_fit: metrics_distributed_fit {}
INFO flwr 2024-07-11 12:55:08,501 | app.py:227 | app_fit: metrics_distributed {}
INFO flwr 2024-07-11 12:55:08,501 | app.py:228 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.39714306305399655), (2, 0.39527291343804777), (3, 0.39508276185041835), (4, 0.3950897001134056), (5, 0.39508927921850634), (6, 0.3936535320244063), (7, 0.3936436977831454), (8, 0.39201319309611876), (9, 0.392020164111833), (10, 0.39201942691876024)]
INFO flwr 2024-07-11 12:55:08,501 | app.py:229 | app_fit: metrics_centralized {'accuracy': [(0, 0.39666666666666667), (1, 0.8), (2, 0.8066666666666666), (3, 0.8033333333333333), (4, 0.8033333333333333), (5, 0.8033333333333333), (6, 0.8033333333333333), (7, 0.8033333333333333), (8, 0.8066666666666666), (9, 0.8066666666666666), (10, 0.8066666666666666)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-1.89135757,  1.0605671 ,  0.85319227,  0.40685213,  0.18939615,
         0.10039014,  0.03322877, -0.0998844 ]]), array([-0.10064692])]
[array([[-1.95684901,  1.05177521,  0.80195852,  0.39426937,  0.20230403,
         0.04933437,  0.02581707, -0.12088737]]), array([0.09198475])]
[array([[-1.9490986 ,  1.04834938,  0.81253737,  0.37091412,  0.23013415,
         0.05128388,  0.0136686 , -0.06402549]]), array([0.02748285])]
[array([[-1.94760737,  1.04751523,  0.81180174,  0.37070979,  0.23020257,
         0.05070172,  0.01382501, -0.06397543]]), array([0.02784331])]
[array([[-1.94762974,  1.04752046,  0.81184269,  0.37073112,  0.23026121,
         0.05069698,  0.01384373, -0.0639655 ]]), array([0.02776045])]
[array([[-1.97420364,  1.01356691,  0.77884946,  0.38371479,  0.19181145,
         0.06974029, -0.02692709, -0.02824386]]), array([0.08046625])]
[array([[-1.97670421,  1.01505224,  0.78027749,  0.38400023,  0.19183931,
         0.07030995, -0.02669959, -0.02858382]]), array([0.0796594])]
[array([[-1.99077297,  0.98020253,  0.80057269,  0.38232792,  0.17005625,
         0.10257604, -0.02393299, -0.00718016]]), array([0.11749524])]
[array([[-1.98974481,  0.97953886,  0.80029578,  0.38217851,  0.16964827,
         0.10277875, -0.0243627 , -0.00682922]]), array([0.11780618])]
[array([[-1.98966257,  0.97947879,  0.8002787 ,  0.38217965,  0.16962569,
         0.10276405, -0.02431738, -0.00680831]]), array([0.11776628])]
>>>>>>>>>>>>>run time:
0.625s
