2023-09-18 17:48:19.409500: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 17:48:19.409669: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 17:48:27,251 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 17:48:27,336 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 17:48:27,336 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 17:48:27,336 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 17:48:27,446 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 17:48:27,446 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:27,461 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4066666666666667}
INFO flwr 2023-09-18 17:48:27,461 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 17:48:27,672 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,695 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 17:48:27,697 | fedavg.py:243 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:27,705 | server.py:125 | fit progress: (1, 0.41418023708039015, {'accuracy': 0.8133333333333334}, 0.24356329999999993)
DEBUG flwr 2023-09-18 17:48:27,705 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,728 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 17:48:27,729 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 17:48:27,729 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,752 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:27,762 | server.py:125 | fit progress: (2, 0.4111976202109015, {'accuracy': 0.82}, 0.30048219999999937)
DEBUG flwr 2023-09-18 17:48:27,762 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,779 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 17:48:27,780 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,800 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:27,810 | server.py:125 | fit progress: (3, 0.41119428454048534, {'accuracy': 0.82}, 0.34833289999999906)
DEBUG flwr 2023-09-18 17:48:27,811 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,830 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 17:48:27,830 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,854 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:27,867 | server.py:125 | fit progress: (4, 0.41119434929758514, {'accuracy': 0.82}, 0.40464940000000027)
DEBUG flwr 2023-09-18 17:48:27,867 | server.py:173 | evaluate_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,887 | server.py:187 | evaluate_round 4 received 3 results and 0 failures
DEBUG flwr 2023-09-18 17:48:27,888 | server.py:223 | fit_round 5: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,908 | server.py:237 | fit_round 5 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:27,919 | server.py:125 | fit progress: (5, 0.4111943491476807, {'accuracy': 0.82}, 0.45751980000000003)
DEBUG flwr 2023-09-18 17:48:27,919 | server.py:173 | evaluate_round 5: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:48:27,938 | server.py:187 | evaluate_round 5 received 3 results and 0 failures
DEBUG flwr 2023-09-18 17:48:27,938 | server.py:223 | fit_round 6: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:48:27,976 | server.py:237 | fit_round 6 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:27,987 | server.py:125 | fit progress: (6, 0.4136749994618637, {'accuracy': 0.8166666666666667}, 0.5257196000000004)
DEBUG flwr 2023-09-18 17:48:27,988 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:48:28,013 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:48:28,014 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:48:28,047 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:28,060 | server.py:125 | fit progress: (7, 0.41345820421283497, {'accuracy': 0.8133333333333334}, 0.5983765999999999)
DEBUG flwr 2023-09-18 17:48:28,061 | server.py:173 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:48:28,097 | server.py:187 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:48:28,097 | server.py:223 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:48:28,139 | server.py:237 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:28,152 | server.py:125 | fit progress: (8, 0.4134559870074696, {'accuracy': 0.8133333333333334}, 0.6893100000000008)
DEBUG flwr 2023-09-18 17:48:28,152 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:48:28,185 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:48:28,185 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:48:28,243 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:28,255 | server.py:125 | fit progress: (9, 0.4126715391115369, {'accuracy': 0.8066666666666666}, 0.7934053999999993)
DEBUG flwr 2023-09-18 17:48:28,256 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:48:28,287 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:48:28,288 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:48:28,331 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:48:28,345 | server.py:125 | fit progress: (10, 0.412670773422949, {'accuracy': 0.8066666666666666}, 0.8831934999999991)
DEBUG flwr 2023-09-18 17:48:28,346 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:48:28,379 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 17:48:28,379 | server.py:147 | FL finished in 0.9167222000000006
INFO flwr 2023-09-18 17:48:28,379 | app.py:218 | app_fit: losses_distributed [(1, 0.39754553511738777), (2, 0.3973522577434778), (3, 0.3973517641425133), (4, 0.3973517622798681), (5, 0.3973517622798681), (6, 0.4116351185809998), (7, 0.4111789358513696), (8, 0.41633655769484385), (9, 0.41616467578070504), (10, 0.4161646498101098)]
INFO flwr 2023-09-18 17:48:28,380 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 17:48:28,380 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 17:48:28,380 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.41418023708039015), (2, 0.4111976202109015), (3, 0.41119428454048534), (4, 0.41119434929758514), (5, 0.4111943491476807), (6, 0.4136749994618637), (7, 0.41345820421283497), (8, 0.4134559870074696), (9, 0.4126715391115369), (10, 0.412670773422949)]
INFO flwr 2023-09-18 17:48:28,380 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.4066666666666667), (1, 0.8133333333333334), (2, 0.82), (3, 0.82), (4, 0.82), (5, 0.82), (6, 0.8166666666666667), (7, 0.8133333333333334), (8, 0.8133333333333334), (9, 0.8066666666666666), (10, 0.8066666666666666)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
>>>>>>>>>>>>> evaluating on server-side
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.08896109,  0.86088776,  0.8812111 ,  0.30575933,  0.12459002,
        -0.03402607,  0.1285684 ,  0.05391493]]), array([0.34230955])]
[array([[-2.08896109,  0.86088776,  0.8812111 ,  0.30575933,  0.12459002,
        -0.03402607,  0.1285684 ,  0.05391493]]), array([0.34230955])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.03998238,  0.86511718,  0.87916667,  0.33263071,  0.11787244,
        -0.03652226,  0.07347398,  0.0411498 ]]), array([0.35016719])]
[array([[-2.03998238,  0.86511718,  0.87916667,  0.33263071,  0.11787244,
        -0.03652226,  0.07347398,  0.0411498 ]]), array([0.35016719])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.03993722,  0.86502072,  0.87942068,  0.33267376,  0.1179446 ,
        -0.03653779,  0.07346174,  0.04117331]]), array([0.34982322])]
[array([[-2.03993722,  0.86502072,  0.87942068,  0.33267376,  0.1179446 ,
        -0.03653779,  0.07346174,  0.04117331]]), array([0.34982322])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.03993866,  0.86502148,  0.87941942,  0.33267265,  0.11794426,
        -0.03653691,  0.07346247,  0.04117416]]), array([0.34982428])]
[array([[-2.03993866,  0.86502148,  0.87941942,  0.33267265,  0.11794426,
        -0.03653691,  0.07346247,  0.04117416]]), array([0.34982428])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.03993866,  0.86502148,  0.87941942,  0.33267265,  0.11794426,
        -0.03653691,  0.07346247,  0.04117416]]), array([0.34982428])]
[array([[-2.03993866,  0.86502148,  0.87941942,  0.33267265,  0.11794426,
        -0.03653691,  0.07346247,  0.04117416]]), array([0.34982428])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.01577012,  0.95352376,  0.75854799,  0.39637908,  0.18200693,
         0.04827578,  0.09436014,  0.04094029]]), array([0.08364011])]
[array([[-2.01577012,  0.95352376,  0.75854799,  0.39637908,  0.18200693,
         0.04827578,  0.09436014,  0.04094029]]), array([0.08364011])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.99618915,  0.92797055,  0.75065124,  0.40527348,  0.21779871,
         0.0573031 ,  0.04333393,  0.05270044]]), array([0.03547001])]
[array([[-1.99618915,  0.92797055,  0.75065124,  0.40527348,  0.21779871,
         0.0573031 ,  0.04333393,  0.05270044]]), array([0.03547001])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.99613292,  0.92774117,  0.75068487,  0.40528584,  0.21788103,
         0.05739549,  0.04323909,  0.05245979]]), array([0.03579827])]
[array([[-1.99613292,  0.92774117,  0.75068487,  0.40528584,  0.21788103,
         0.05739549,  0.04323909,  0.05245979]]), array([0.03579827])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.96217207,  0.94067059,  0.75230847,  0.39872963,  0.19574147,
         0.07687781,  0.02663513,  0.02952516]]), array([0.03913101])]
[array([[-1.96217207,  0.94067059,  0.75230847,  0.39872963,  0.19574147,
         0.07687781,  0.02663513,  0.02952516]]), array([0.03913101])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.96221092,  0.94074023,  0.75232214,  0.39874217,  0.19569685,
         0.0768048 ,  0.02665379,  0.02955747]]), array([0.0391138])]
[array([[-1.96221092,  0.94074023,  0.75232214,  0.39874217,  0.19569685,
         0.0768048 ,  0.02665379,  0.02955747]]), array([0.0391138])]
>>>>>>>>>>>>>run time:
0.609375s
