2023-09-18 18:05:55.357560: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:05:55.357728: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:06:02,867 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:06:02,923 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:06:02,923 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:06:02,923 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:06:03,967 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:06:03,968 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:03,984 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4033333333333333}
INFO flwr 2023-09-18 18:06:03,984 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:06:04,157 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:04,181 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:06:04,183 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,191 | server.py:125 | fit progress: (1, 0.4427923581037729, {'accuracy': 0.78}, 0.20635009999999987)
DEBUG flwr 2023-09-18 18:06:04,191 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:04,212 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:06:04,212 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:06:04,212 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:04,232 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,242 | server.py:125 | fit progress: (2, 0.4355941821073831, {'accuracy': 0.79}, 0.2574650999999992)
DEBUG flwr 2023-09-18 18:06:04,242 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:04,259 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:06:04,260 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:04,280 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,290 | server.py:125 | fit progress: (3, 0.4356261228840277, {'accuracy': 0.79}, 0.30560919999999925)
DEBUG flwr 2023-09-18 18:06:04,291 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:04,308 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:06:04,308 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:04,325 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,335 | server.py:125 | fit progress: (4, 0.4356262728656295, {'accuracy': 0.79}, 0.3509150999999999)
DEBUG flwr 2023-09-18 18:06:04,335 | server.py:173 | evaluate_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:04,351 | server.py:187 | evaluate_round 4 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:06:04,351 | server.py:223 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:04,383 | server.py:237 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,394 | server.py:125 | fit progress: (5, 0.4402157266303256, {'accuracy': 0.7866666666666666}, 0.40975489999999937)
DEBUG flwr 2023-09-18 18:06:04,394 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:04,417 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:06:04,417 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:04,451 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,462 | server.py:125 | fit progress: (6, 0.4402046598784589, {'accuracy': 0.7866666666666666}, 0.47701689999999886)
DEBUG flwr 2023-09-18 18:06:04,462 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:04,481 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:06:04,482 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:04,510 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,523 | server.py:125 | fit progress: (7, 0.44020475360381645, {'accuracy': 0.7866666666666666}, 0.5385346000000002)
DEBUG flwr 2023-09-18 18:06:04,524 | server.py:173 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:04,547 | server.py:187 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:06:04,547 | server.py:223 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:04,580 | server.py:237 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,594 | server.py:125 | fit progress: (8, 0.440204753114842, {'accuracy': 0.7866666666666666}, 0.6097374000000002)
DEBUG flwr 2023-09-18 18:06:04,594 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:04,618 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:06:04,618 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:04,655 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,667 | server.py:125 | fit progress: (9, 0.44053091216465173, {'accuracy': 0.7833333333333333}, 0.6825537999999991)
DEBUG flwr 2023-09-18 18:06:04,667 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:04,691 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:06:04,691 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:04,724 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:04,735 | server.py:125 | fit progress: (10, 0.44053064230222216, {'accuracy': 0.7833333333333333}, 0.7505904000000001)
DEBUG flwr 2023-09-18 18:06:04,736 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:04,759 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:06:04,760 | server.py:147 | FL finished in 0.7747765999999991
INFO flwr 2023-09-18 18:06:04,760 | app.py:218 | app_fit: losses_distributed [(1, 0.4096006825566292), (2, 0.4090842753648758), (3, 0.40907941944897175), (4, 0.40907938219606876), (5, 0.40680245700336637), (6, 0.40680317722615744), (7, 0.4068031729686828), (8, 0.4109225643532617), (9, 0.41070921378476277), (10, 0.41070918909140997)]
INFO flwr 2023-09-18 18:06:04,760 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:06:04,760 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:06:04,760 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.4427923581037729), (2, 0.4355941821073831), (3, 0.4356261228840277), (4, 0.4356262728656295), (5, 0.4402157266303256), (6, 0.4402046598784589), (7, 0.44020475360381645), (8, 0.440204753114842), (9, 0.44053091216465173), (10, 0.44053064230222216)]
INFO flwr 2023-09-18 18:06:04,760 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.4033333333333333), (1, 0.78), (2, 0.79), (3, 0.79), (4, 0.79), (5, 0.7866666666666666), (6, 0.7866666666666666), (7, 0.7866666666666666), (8, 0.7866666666666666), (9, 0.7833333333333333), (10, 0.7833333333333333)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.04294386,  0.94496585,  0.76481205,  0.36450525,  0.22169526,
        -0.04541875,  0.0408604 , -0.0170754 ]]), array([0.22391909])]
[array([[-1.95757325,  0.92354844,  0.77514111,  0.35705756,  0.23288161,
        -0.03801366,  0.07349924,  0.02891362]]), array([0.11247607])]
[array([[-1.95907029,  0.92433404,  0.77556023,  0.35716964,  0.23357196,
        -0.03819942,  0.07354913,  0.02906589]]), array([0.11185306])]
[array([[-1.95908886,  0.92433792,  0.77557879,  0.35717436,  0.23356339,
        -0.03819369,  0.0735337 ,  0.02907071]]), array([0.11186232])]
[array([[-1.98285444,  0.98910453,  0.85439121,  0.3914196 ,  0.24611847,
         0.04424978,  0.07363682, -0.03149549]]), array([-0.10712926])]
[array([[-1.98235587,  0.98886937,  0.85430724,  0.39135642,  0.24586643,
         0.04437257,  0.07359719, -0.0315537 ]]), array([-0.10699772])]
[array([[-1.98235803,  0.98887065,  0.8543077 ,  0.39135696,  0.24586603,
         0.04437199,  0.07359725, -0.03155418]]), array([-0.10699661])]
[array([[-1.98235802,  0.98887064,  0.8543077 ,  0.39135696,  0.24586603,
         0.04437199,  0.07359725, -0.03155418]]), array([-0.10699661])]
[array([[-1.97303454,  0.98486689,  0.82765023,  0.3819099 ,  0.24093111,
         0.07467456,  0.04124658, -0.01861028]]), array([-0.09107076])]
[array([[-1.97304262,  0.9848782 ,  0.82765169,  0.38190708,  0.24093261,
         0.07467057,  0.04123914, -0.01860376]]), array([-0.09106208])]
>>>>>>>>>>>>>run time:
0.40625s
