2023-09-18 18:04:04.906120: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:04:04.906300: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:04:12,488 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:04:12,547 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:04:12,547 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:04:12,547 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:04:13,530 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:04:13,530 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:13,545 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.47}
INFO flwr 2023-09-18 18:04:13,545 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:04:13,771 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,793 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:04:13,795 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:13,803 | server.py:125 | fit progress: (1, 0.35721404678774377, {'accuracy': 0.8266666666666667}, 0.2568701999999998)
DEBUG flwr 2023-09-18 18:04:13,803 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,825 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:04:13,825 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:04:13,825 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,847 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:13,857 | server.py:125 | fit progress: (2, 0.3491187666684662, {'accuracy': 0.8333333333333334}, 0.31101680000000087)
DEBUG flwr 2023-09-18 18:04:13,857 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,874 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:04:13,874 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,894 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:13,904 | server.py:125 | fit progress: (3, 0.34911869478145785, {'accuracy': 0.8333333333333334}, 0.3575215000000007)
DEBUG flwr 2023-09-18 18:04:13,904 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,921 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:04:13,921 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,939 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:13,948 | server.py:125 | fit progress: (4, 0.34911174217113794, {'accuracy': 0.8333333333333334}, 0.4021442000000004)
DEBUG flwr 2023-09-18 18:04:13,949 | server.py:173 | evaluate_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,966 | server.py:187 | evaluate_round 4 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:04:13,967 | server.py:223 | fit_round 5: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:13,985 | server.py:237 | fit_round 5 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:13,995 | server.py:125 | fit progress: (5, 0.3491125393219007, {'accuracy': 0.8333333333333334}, 0.44911869999999965)
DEBUG flwr 2023-09-18 18:04:13,995 | server.py:173 | evaluate_round 5: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:14,013 | server.py:187 | evaluate_round 5 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:04:14,013 | server.py:223 | fit_round 6: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:14,033 | server.py:237 | fit_round 6 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:14,042 | server.py:125 | fit progress: (6, 0.3491118587771992, {'accuracy': 0.8333333333333334}, 0.4966483000000004)
DEBUG flwr 2023-09-18 18:04:14,043 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:14,065 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:04:14,066 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:14,090 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:14,101 | server.py:125 | fit progress: (7, 0.35160644970242333, {'accuracy': 0.8166666666666667}, 0.5547218000000012)
DEBUG flwr 2023-09-18 18:04:14,101 | server.py:173 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:14,127 | server.py:187 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:04:14,127 | server.py:223 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:14,159 | server.py:237 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:14,171 | server.py:125 | fit progress: (8, 0.35160461343949073, {'accuracy': 0.8166666666666667}, 0.6243081999999998)
DEBUG flwr 2023-09-18 18:04:14,171 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:14,201 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:04:14,201 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:14,244 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:14,257 | server.py:125 | fit progress: (9, 0.35421263380609985, {'accuracy': 0.8166666666666667}, 0.7112033000000011)
DEBUG flwr 2023-09-18 18:04:14,257 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:14,291 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:04:14,291 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:14,332 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:14,345 | server.py:125 | fit progress: (10, 0.3542130008736523, {'accuracy': 0.8166666666666667}, 0.7998346999999999)
DEBUG flwr 2023-09-18 18:04:14,346 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:14,373 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:04:14,373 | server.py:147 | FL finished in 0.8276286000000006
INFO flwr 2023-09-18 18:04:14,374 | app.py:218 | app_fit: losses_distributed [(1, 0.3891330361366272), (2, 0.388087535277009), (3, 0.38808767683804035), (4, 0.3880869150161743), (5, 0.38808707520365715), (6, 0.4070251853693099), (7, 0.40413776465824675), (8, 0.4079346516302654), (9, 0.40757541145597187), (10, 0.4075753825051444)]
INFO flwr 2023-09-18 18:04:14,374 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:04:14,374 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:04:14,374 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.35721404678774377), (2, 0.3491187666684662), (3, 0.34911869478145785), (4, 0.34911174217113794), (5, 0.3491125393219007), (6, 0.3491118587771992), (7, 0.35160644970242333), (8, 0.35160461343949073), (9, 0.35421263380609985), (10, 0.3542130008736523)]
INFO flwr 2023-09-18 18:04:14,374 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.47), (1, 0.8266666666666667), (2, 0.8333333333333334), (3, 0.8333333333333334), (4, 0.8333333333333334), (5, 0.8333333333333334), (6, 0.8333333333333334), (7, 0.8166666666666667), (8, 0.8166666666666667), (9, 0.8166666666666667), (10, 0.8166666666666667)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.03897268,  0.98123828,  0.91475363,  0.39923841,  0.01140071,
         0.20562226,  0.06386057, -0.05415499]]), array([-0.05428233])]
[array([[-2.08605404,  1.0027955 ,  0.95951781,  0.45649932,  0.05309331,
         0.15304661,  0.07736085,  0.00210647]]), array([-0.19404082])]
[array([[-2.08604325,  1.00276904,  0.95952428,  0.45645772,  0.05312092,
         0.15302949,  0.07730585,  0.00213105]]), array([-0.19396341])]
[array([[-2.08620148,  1.00286181,  0.95962935,  0.45657254,  0.05310895,
         0.15304487,  0.07729805,  0.00216968]]), array([-0.19412253])]
[array([[-2.08617353,  1.00285083,  0.95961378,  0.45653413,  0.05308842,
         0.15305615,  0.07727593,  0.00221767]]), array([-0.19413217])]
[array([[-2.08619915,  1.0028596 ,  0.95962772,  0.45656983,  0.05310794,
         0.15304558,  0.07729789,  0.00217122]]), array([-0.1941212])]
[array([[-2.03938411,  1.00204276,  0.86012361,  0.40497694,  0.17472574,
         0.09628129, -0.01825588,  0.01739182]]), array([-0.03158973])]
[array([[-2.039666  ,  1.00211329,  0.86019787,  0.40498196,  0.17480486,
         0.09633418, -0.01838315,  0.01743399]]), array([-0.03148856])]
[array([[-2.02014657,  1.01977084,  0.81859088,  0.41207074,  0.16041166,
         0.10328684, -0.06017826,  0.01537154]]), array([0.04371315])]
[array([[-2.02026467,  1.01977049,  0.81857141,  0.41208893,  0.16033742,
         0.10333012, -0.06013425,  0.01535358]]), array([0.04387423])]
>>>>>>>>>>>>>run time:
0.46875s
