2023-09-18 18:08:10.198005: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:08:10.198174: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:08:17,754 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:08:17,812 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:08:17,812 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:08:17,812 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:08:18,712 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:08:18,712 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:18,728 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.49333333333333335}
INFO flwr 2023-09-18 18:08:18,728 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:08:18,938 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:08:18,961 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:08:18,963 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:18,970 | server.py:125 | fit progress: (1, 0.37280243510689853, {'accuracy': 0.8333333333333334}, 0.24186940000000057)
DEBUG flwr 2023-09-18 18:08:18,970 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:08:18,994 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:08:18,994 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:08:18,995 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:08:19,013 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,022 | server.py:125 | fit progress: (2, 0.37861482383288875, {'accuracy': 0.82}, 0.2939391000000011)
DEBUG flwr 2023-09-18 18:08:19,023 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:08:19,038 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:08:19,038 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:08:19,058 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,068 | server.py:125 | fit progress: (3, 0.3786052799785293, {'accuracy': 0.82}, 0.33927399999999963)
DEBUG flwr 2023-09-18 18:08:19,068 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:08:19,084 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:08:19,085 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:08:19,102 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,112 | server.py:125 | fit progress: (4, 0.3786054546097795, {'accuracy': 0.82}, 0.38395189999999957)
DEBUG flwr 2023-09-18 18:08:19,112 | server.py:173 | evaluate_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:08:19,128 | server.py:187 | evaluate_round 4 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:08:19,128 | server.py:223 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:08:19,160 | server.py:237 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,171 | server.py:125 | fit progress: (5, 0.3844741821383516, {'accuracy': 0.8166666666666667}, 0.44262580000000007)
DEBUG flwr 2023-09-18 18:08:19,171 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:08:19,196 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:08:19,197 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:08:19,224 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,236 | server.py:125 | fit progress: (6, 0.38446548014916987, {'accuracy': 0.8166666666666667}, 0.5076200000000011)
DEBUG flwr 2023-09-18 18:08:19,236 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:08:19,263 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:08:19,263 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:08:19,294 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,306 | server.py:125 | fit progress: (7, 0.3844648387289751, {'accuracy': 0.8166666666666667}, 0.5771480000000011)
DEBUG flwr 2023-09-18 18:08:19,306 | server.py:173 | evaluate_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:08:19,332 | server.py:187 | evaluate_round 7 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:08:19,333 | server.py:223 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:08:19,371 | server.py:237 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,383 | server.py:125 | fit progress: (8, 0.38828824440986587, {'accuracy': 0.8133333333333334}, 0.6547367000000008)
DEBUG flwr 2023-09-18 18:08:19,383 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:08:19,412 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:08:19,412 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:08:19,449 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,461 | server.py:125 | fit progress: (9, 0.38827734765556216, {'accuracy': 0.8133333333333334}, 0.7329939000000003)
DEBUG flwr 2023-09-18 18:08:19,461 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:08:19,486 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:08:19,486 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:08:19,517 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:08:19,529 | server.py:125 | fit progress: (10, 0.38827634260597754, {'accuracy': 0.8133333333333334}, 0.8008509000000004)
DEBUG flwr 2023-09-18 18:08:19,530 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:08:19,555 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:08:19,555 | server.py:147 | FL finished in 0.8268692000000009
INFO flwr 2023-09-18 18:08:19,556 | app.py:218 | app_fit: losses_distributed [(1, 0.3863877058029175), (2, 0.38530953973531723), (3, 0.3853086940944195), (4, 0.38530873134732246), (5, 0.39586066490127925), (6, 0.3958610104663031), (7, 0.4124311821801322), (8, 0.41144711886133467), (9, 0.4114470830985478), (10, 0.41144707330635616)]
INFO flwr 2023-09-18 18:08:19,556 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:08:19,556 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:08:19,556 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.37280243510689853), (2, 0.37861482383288875), (3, 0.3786052799785293), (4, 0.3786054546097795), (5, 0.3844741821383516), (6, 0.38446548014916987), (7, 0.3844648387289751), (8, 0.38828824440986587), (9, 0.38827734765556216), (10, 0.38827634260597754)]
INFO flwr 2023-09-18 18:08:19,556 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.49333333333333335), (1, 0.8333333333333334), (2, 0.82), (3, 0.82), (4, 0.82), (5, 0.8166666666666667), (6, 0.8166666666666667), (7, 0.8166666666666667), (8, 0.8133333333333334), (9, 0.8133333333333334), (10, 0.8133333333333334)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.12523324,  1.04217054,  0.93555734,  0.50229721,  0.13152833,
         0.1217038 , -0.01746851, -0.1503077 ]]), array([0.08039173])]
[array([[-2.13149349,  0.98366857,  0.91223832,  0.49866291,  0.14796014,
         0.17248614,  0.03936654, -0.06501931]]), array([0.00073925])]
[array([[-2.13172425,  0.98391227,  0.91212435,  0.49881011,  0.14784866,
         0.17245103,  0.03932071, -0.06508512]]), array([0.00099969])]
[array([[-2.1317046 ,  0.98388787,  0.91213643,  0.49878982,  0.14784146,
         0.17243419,  0.03932849, -0.06506695]]), array([0.00100796])]
[array([[-2.05328142,  1.0388031 ,  0.83895782,  0.43750327,  0.19700745,
         0.15149276,  0.06155099, -0.00621873]]), array([-0.14708138])]
[array([[-2.0531237 ,  1.03861478,  0.83896818,  0.43735738,  0.19706434,
         0.15144187,  0.06149144, -0.00651612]]), array([-0.14664176])]
[array([[-2.05312787,  1.03862399,  0.8389746 ,  0.43737005,  0.19707051,
         0.15143712,  0.06149649, -0.00651872]]), array([-0.14667225])]
[array([[-1.95191931,  1.00777427,  0.78498908,  0.39368037,  0.19596442,
         0.10511713, -0.0173056 ,  0.00985308]]), array([-0.02920318])]
[array([[-1.95210767,  1.00851277,  0.78504952,  0.39380701,  0.19562027,
         0.10534799, -0.01704842,  0.01007046]]), array([-0.03010968])]
[array([[-1.952122  ,  1.0084995 ,  0.78505337,  0.39377301,  0.19562142,
         0.10533706, -0.0170571 ,  0.01003655]]), array([-0.03000063])]
>>>>>>>>>>>>>run time:
0.703125s
