2024-07-11 12:55:48.526429: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2024-07-11 12:55:48.526626: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2024-07-11 12:55:58,148 | app.py:165 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2024-07-11 12:55:58,233 | app.py:179 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2024-07-11 12:55:58,234 | server.py:89 | Initializing global parameters
INFO flwr 2024-07-11 12:55:58,234 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2024-07-11 12:56:00,139 | server.py:280 | Received initial parameters from one random client
INFO flwr 2024-07-11 12:56:00,139 | server.py:91 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:00,156 | server.py:98 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.49333333333333335}
INFO flwr 2024-07-11 12:56:00,156 | server.py:104 | FL starting
DEBUG flwr 2024-07-11 12:56:00,800 | server.py:227 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2024-07-11 12:56:00,855 | server.py:241 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2024-07-11 12:56:00,858 | fedavgm.py:198 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:00,866 | server.py:131 | fit progress: (1, 0.37349710547749476, {'accuracy': 0.81}, 0.7099072999999994)
DEBUG flwr 2024-07-11 12:56:00,867 | server.py:178 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:56:00,909 | server.py:192 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2024-07-11 12:56:00,909 | fedavg.py:273 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2024-07-11 12:56:00,909 | server.py:227 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:56:00,987 | server.py:241 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:00,998 | server.py:131 | fit progress: (2, 0.3785730033205655, {'accuracy': 0.82}, 0.8418677999999993)
DEBUG flwr 2024-07-11 12:56:00,998 | server.py:178 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:56:01,022 | server.py:192 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:56:01,023 | server.py:227 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:56:01,082 | server.py:241 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:01,094 | server.py:131 | fit progress: (3, 0.3786055695532, {'accuracy': 0.82}, 0.9378203000000003)
DEBUG flwr 2024-07-11 12:56:01,095 | server.py:178 | evaluate_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:56:01,166 | server.py:192 | evaluate_round 3 received 4 results and 0 failures
DEBUG flwr 2024-07-11 12:56:01,167 | server.py:227 | fit_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,232 | server.py:241 | fit_round 4 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:01,244 | server.py:131 | fit progress: (4, 0.3859297997142501, {'accuracy': 0.82}, 1.0875657999999984)
DEBUG flwr 2024-07-11 12:56:01,244 | server.py:178 | evaluate_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,288 | server.py:192 | evaluate_round 4 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:56:01,288 | server.py:227 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,332 | server.py:241 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:01,344 | server.py:131 | fit progress: (5, 0.38633908540193074, {'accuracy': 0.8166666666666667}, 1.187085399999999)
DEBUG flwr 2024-07-11 12:56:01,344 | server.py:178 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,375 | server.py:192 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:56:01,375 | server.py:227 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,420 | server.py:241 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:01,433 | server.py:131 | fit progress: (6, 0.3860245571533122, {'accuracy': 0.82}, 1.2758427)
DEBUG flwr 2024-07-11 12:56:01,433 | server.py:178 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,461 | server.py:192 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:56:01,461 | server.py:227 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,513 | server.py:241 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:01,525 | server.py:131 | fit progress: (7, 0.38630654752014426, {'accuracy': 0.8166666666666667}, 1.3686650999999994)
DEBUG flwr 2024-07-11 12:56:01,525 | server.py:178 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,555 | server.py:192 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:56:01,556 | server.py:227 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,596 | server.py:241 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:01,608 | server.py:131 | fit progress: (8, 0.38602371880864295, {'accuracy': 0.82}, 1.4516448999999998)
DEBUG flwr 2024-07-11 12:56:01,609 | server.py:178 | evaluate_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:56:01,647 | server.py:192 | evaluate_round 8 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:56:01,647 | server.py:227 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:56:01,709 | server.py:241 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:01,722 | server.py:131 | fit progress: (9, 0.38843010542633055, {'accuracy': 0.8133333333333334}, 1.5660904999999996)
DEBUG flwr 2024-07-11 12:56:01,723 | server.py:178 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:56:01,754 | server.py:192 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:56:01,754 | server.py:227 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:56:01,791 | server.py:241 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:56:01,804 | server.py:131 | fit progress: (10, 0.3882797712597625, {'accuracy': 0.8133333333333334}, 1.6475802999999996)
DEBUG flwr 2024-07-11 12:56:01,804 | server.py:178 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:56:01,835 | server.py:192 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2024-07-11 12:56:01,835 | server.py:153 | FL finished in 1.678563500000001
INFO flwr 2024-07-11 12:56:01,836 | app.py:225 | app_fit: losses_distributed [(1, 0.3866398762911558), (2, 0.38530877232551575), (3, 0.4208066151900725), (4, 0.41236985449133245), (5, 0.41236476857086707), (6, 0.4123677184869503), (7, 0.4123630873088179), (8, 0.41236772002844974), (9, 0.41144695367131917), (10, 0.4114489759717669)]
INFO flwr 2024-07-11 12:56:01,836 | app.py:226 | app_fit: metrics_distributed_fit {}
INFO flwr 2024-07-11 12:56:01,836 | app.py:227 | app_fit: metrics_distributed {}
INFO flwr 2024-07-11 12:56:01,836 | app.py:228 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.37349710547749476), (2, 0.3785730033205655), (3, 0.3786055695532), (4, 0.3859297997142501), (5, 0.38633908540193074), (6, 0.3860245571533122), (7, 0.38630654752014426), (8, 0.38602371880864295), (9, 0.38843010542633055), (10, 0.3882797712597625)]
INFO flwr 2024-07-11 12:56:01,836 | app.py:229 | app_fit: metrics_centralized {'accuracy': [(0, 0.49333333333333335), (1, 0.81), (2, 0.82), (3, 0.82), (4, 0.82), (5, 0.8166666666666667), (6, 0.82), (7, 0.8166666666666667), (8, 0.82), (9, 0.8133333333333334), (10, 0.8133333333333334)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.14413731,  0.96368065,  0.9621154 ,  0.57225157,  0.08079034,
         0.15307089,  0.13648584, -0.0629818 ]]), array([-0.08791463])]
[array([[-2.13140298,  0.98403967,  0.91249854,  0.49810151,  0.14771402,
         0.17208583,  0.03956637, -0.06549019]]), array([0.00158419])]
[array([[-2.13168709,  0.9838654 ,  0.91216145,  0.49876442,  0.14783576,
         0.1724185 ,  0.03933611, -0.06504724]]), array([0.00100721])]
[array([[-1.94041736,  0.99956159,  0.79626575,  0.3931259 ,  0.15800451,
         0.09047504, -0.02053222,  0.00514331]]), array([0.01757903])]
[array([[-1.93796631,  0.99830662,  0.79422212,  0.3912857 ,  0.16099975,
         0.08688944, -0.0208746 ,  0.0082728 ]]), array([0.02226685])]
[array([[-1.94099676,  0.99784931,  0.79444458,  0.39117891,  0.15791585,
         0.08828397, -0.02029169,  0.00536935]]), array([0.02694664])]
[array([[-1.93861504,  0.99913521,  0.7942762 ,  0.3909377 ,  0.1601692 ,
         0.08753459, -0.02202022,  0.00743093]]), array([0.02490745])]
[array([[-1.94099205,  0.99790276,  0.79446437,  0.39119209,  0.15791084,
         0.0883424 , -0.02030781,  0.0053523 ]]), array([0.02682292])]
[array([[-1.94945114,  1.00880651,  0.78542756,  0.39387445,  0.19702845,
         0.10543286, -0.01710308,  0.01145961]]), array([-0.03541244])]
[array([[-1.95195988,  1.00690163,  0.78458948,  0.39397688,  0.19548997,
         0.10533409, -0.01683922,  0.01009589]]), array([-0.02897796])]
>>>>>>>>>>>>>run time:
0.53125s
