2023-09-18 18:06:19.902314: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:06:19.902490: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:06:27,482 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:06:27,547 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:06:27,548 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:06:27,548 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:06:28,502 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:06:28,502 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:28,518 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.42333333333333334}
INFO flwr 2023-09-18 18:06:28,518 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:06:28,720 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:28,746 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:06:28,748 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:28,756 | server.py:125 | fit progress: (1, 0.43892239160018115, {'accuracy': 0.7966666666666666}, 0.23721489999999967)
DEBUG flwr 2023-09-18 18:06:28,756 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:28,777 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:06:28,778 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:06:28,778 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:28,800 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:28,809 | server.py:125 | fit progress: (2, 0.4351479875290541, {'accuracy': 0.8}, 0.2906583999999999)
DEBUG flwr 2023-09-18 18:06:28,810 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:28,825 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:06:28,826 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:28,846 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:28,855 | server.py:125 | fit progress: (3, 0.43515016068171, {'accuracy': 0.8}, 0.336371999999999)
DEBUG flwr 2023-09-18 18:06:28,856 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:28,872 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:06:28,872 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:28,892 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:28,901 | server.py:125 | fit progress: (4, 0.43515012317778684, {'accuracy': 0.8}, 0.38225390000000026)
DEBUG flwr 2023-09-18 18:06:28,902 | server.py:173 | evaluate_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:28,925 | server.py:187 | evaluate_round 4 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:06:28,925 | server.py:223 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:28,952 | server.py:237 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:28,963 | server.py:125 | fit progress: (5, 0.4390617363047448, {'accuracy': 0.7966666666666666}, 0.4447095999999995)
DEBUG flwr 2023-09-18 18:06:28,963 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:28,987 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:06:28,987 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:29,020 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:29,037 | server.py:125 | fit progress: (6, 0.43904093871288563, {'accuracy': 0.7966666666666666}, 0.5184043999999997)
DEBUG flwr 2023-09-18 18:06:29,037 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:29,064 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:06:29,065 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:29,095 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:29,106 | server.py:125 | fit progress: (7, 0.4390426976415997, {'accuracy': 0.7966666666666666}, 0.5873071000000003)
DEBUG flwr 2023-09-18 18:06:29,107 | server.py:173 | evaluate_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:29,133 | server.py:187 | evaluate_round 7 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:06:29,134 | server.py:223 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:29,167 | server.py:237 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:29,179 | server.py:125 | fit progress: (8, 0.4371849034147377, {'accuracy': 0.8033333333333333}, 0.6602040999999996)
DEBUG flwr 2023-09-18 18:06:29,180 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:29,204 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:06:29,205 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:29,241 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:29,254 | server.py:125 | fit progress: (9, 0.43722452839798603, {'accuracy': 0.8033333333333333}, 0.7354454999999991)
DEBUG flwr 2023-09-18 18:06:29,254 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:29,279 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:06:29,280 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:29,311 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:29,323 | server.py:125 | fit progress: (10, 0.43722316590956223, {'accuracy': 0.8033333333333333}, 0.8041125000000005)
DEBUG flwr 2023-09-18 18:06:29,323 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:29,351 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:06:29,352 | server.py:147 | FL finished in 0.8326996999999992
INFO flwr 2023-09-18 18:06:29,352 | app.py:218 | app_fit: losses_distributed [(1, 0.40925169736146927), (2, 0.40899021178483963), (3, 0.40899066627025604), (4, 0.40809749208745505), (5, 0.40673794632866267), (6, 0.40673981394086567), (7, 0.41583782817636217), (8, 0.415378223998206), (9, 0.4153766291482108), (10, 0.4153773005519594)]
INFO flwr 2023-09-18 18:06:29,352 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:06:29,352 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:06:29,352 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.43892239160018115), (2, 0.4351479875290541), (3, 0.43515016068171), (4, 0.43515012317778684), (5, 0.4390617363047448), (6, 0.43904093871288563), (7, 0.4390426976415997), (8, 0.4371849034147377), (9, 0.43722452839798603), (10, 0.43722316590956223)]
INFO flwr 2023-09-18 18:06:29,352 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.42333333333333334), (1, 0.7966666666666666), (2, 0.8), (3, 0.8), (4, 0.8), (5, 0.7966666666666666), (6, 0.7966666666666666), (7, 0.7966666666666666), (8, 0.8033333333333333), (9, 0.8033333333333333), (10, 0.8033333333333333)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.05361551,  1.04724206,  0.78444345,  0.36319491,  0.31405139,
         0.24411356,  0.02454484,  0.056696  ]]), array([-0.14158789])]
[array([[-1.97851719,  0.98487751,  0.75609771,  0.39034974,  0.31710609,
         0.23294421,  0.02092959,  0.05553156]]), array([-0.18589736])]
[array([[-1.97851478,  0.98485824,  0.75611841,  0.39031451,  0.31700232,
         0.23279459,  0.02097644,  0.05565071]]), array([-0.18578963])]
[array([[-1.97851596,  0.98485627,  0.75611861,  0.39031499,  0.31700282,
         0.23279685,  0.02097571,  0.05565113]]), array([-0.18578917])]
[array([[-2.02603436,  1.02648355,  0.78832246,  0.37485638,  0.21714688,
         0.21154781,  0.00590165, -0.01829927]]), array([0.01961211])]
[array([[-2.02478569,  1.02618309,  0.78786053,  0.37436053,  0.21731106,
         0.21161494,  0.00597232, -0.01822197]]), array([0.01899558])]
[array([[-2.02482077,  1.02621986,  0.78784025,  0.37436789,  0.21730507,
         0.21161072,  0.0059586 , -0.01823093]]), array([0.01908021])]
[array([[-1.94276807e+00,  1.00157698e+00,  7.68456953e-01,
         3.49560955e-01,  2.26516147e-01,  2.01669024e-01,
         1.87263567e-02, -6.61045178e-04]]), array([-0.09617276])]
[array([[-1.94366830e+00,  1.00268631e+00,  7.69235268e-01,
         3.49185241e-01,  2.27352533e-01,  2.01282128e-01,
         1.95456045e-02,  3.48180744e-05]]), array([-0.09778693])]
[array([[-1.94346078e+00,  1.00237484e+00,  7.69016416e-01,
         3.49108654e-01,  2.27027875e-01,  2.01166155e-01,
         1.93798891e-02, -2.36711801e-05]]), array([-0.09688424])]
>>>>>>>>>>>>>run time:
0.40625s
