2024-07-11 12:53:03.149370: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2024-07-11 12:53:03.149622: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2024-07-11 12:53:11,630 | app.py:165 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2024-07-11 12:53:11,724 | app.py:179 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2024-07-11 12:53:11,724 | server.py:89 | Initializing global parameters
INFO flwr 2024-07-11 12:53:11,724 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2024-07-11 12:53:13,009 | server.py:280 | Received initial parameters from one random client
INFO flwr 2024-07-11 12:53:13,010 | server.py:91 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,026 | server.py:98 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4166666666666667}
INFO flwr 2024-07-11 12:53:13,026 | server.py:104 | FL starting
DEBUG flwr 2024-07-11 12:53:13,238 | server.py:227 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:13,260 | server.py:241 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2024-07-11 12:53:13,262 | fedavgm.py:198 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,270 | server.py:131 | fit progress: (1, 0.42218090716583806, {'accuracy': 0.7866666666666666}, 0.24389960000000066)
DEBUG flwr 2024-07-11 12:53:13,270 | server.py:178 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:13,291 | server.py:192 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2024-07-11 12:53:13,292 | fedavg.py:273 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2024-07-11 12:53:13,292 | server.py:227 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:13,313 | server.py:241 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,324 | server.py:131 | fit progress: (2, 0.42459381430064413, {'accuracy': 0.7766666666666666}, 0.2974962000000012)
DEBUG flwr 2024-07-11 12:53:13,324 | server.py:178 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:13,342 | server.py:192 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:53:13,343 | server.py:227 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:13,361 | server.py:241 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,372 | server.py:131 | fit progress: (3, 0.42459537144356635, {'accuracy': 0.7766666666666666}, 0.34557649999999995)
DEBUG flwr 2024-07-11 12:53:13,372 | server.py:178 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:13,389 | server.py:192 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:53:13,389 | server.py:227 | fit_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:53:13,419 | server.py:241 | fit_round 4 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,429 | server.py:131 | fit progress: (4, 0.42764342270179195, {'accuracy': 0.79}, 0.4037108000000007)
DEBUG flwr 2024-07-11 12:53:13,430 | server.py:178 | evaluate_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:53:13,450 | server.py:192 | evaluate_round 4 received 4 results and 0 failures
DEBUG flwr 2024-07-11 12:53:13,450 | server.py:227 | fit_round 5: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:53:13,475 | server.py:241 | fit_round 5 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,487 | server.py:131 | fit progress: (5, 0.4276294975432371, {'accuracy': 0.79}, 0.46129650000000133)
DEBUG flwr 2024-07-11 12:53:13,488 | server.py:178 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:13,512 | server.py:192 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:53:13,512 | server.py:227 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:13,544 | server.py:241 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,556 | server.py:131 | fit progress: (6, 0.4300362567940795, {'accuracy': 0.7933333333333333}, 0.5295293000000001)
DEBUG flwr 2024-07-11 12:53:13,556 | server.py:178 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:13,578 | server.py:192 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:53:13,578 | server.py:227 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:13,608 | server.py:241 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,619 | server.py:131 | fit progress: (7, 0.43006175440224886, {'accuracy': 0.7933333333333333}, 0.5937528000000007)
DEBUG flwr 2024-07-11 12:53:13,620 | server.py:178 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:13,644 | server.py:192 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:53:13,645 | server.py:227 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:13,679 | server.py:241 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,691 | server.py:131 | fit progress: (8, 0.43006120592976305, {'accuracy': 0.7933333333333333}, 0.6648021000000011)
DEBUG flwr 2024-07-11 12:53:13,691 | server.py:178 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:53:13,720 | server.py:192 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:53:13,721 | server.py:227 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:53:13,761 | server.py:241 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,775 | server.py:131 | fit progress: (9, 0.42923387396620477, {'accuracy': 0.78}, 0.748693900000001)
DEBUG flwr 2024-07-11 12:53:13,775 | server.py:178 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:53:13,805 | server.py:192 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:53:13,805 | server.py:227 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:53:13,842 | server.py:241 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:13,854 | server.py:131 | fit progress: (10, 0.42923178480092666, {'accuracy': 0.78}, 0.8282508000000011)
DEBUG flwr 2024-07-11 12:53:13,854 | server.py:178 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:53:13,882 | server.py:192 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2024-07-11 12:53:13,883 | server.py:153 | FL finished in 0.8569973000000015
INFO flwr 2024-07-11 12:53:13,883 | app.py:225 | app_fit: losses_distributed [(1, 0.41895109973847866), (2, 0.4162928145378828), (3, 0.41629466973245144), (4, 0.4066488792498906), (5, 0.4056495215211596), (6, 0.40544318159421283), (7, 0.40544232938970837), (8, 0.40710230469703673), (9, 0.4069705184016909), (10, 0.4069710297243936)]
INFO flwr 2024-07-11 12:53:13,883 | app.py:226 | app_fit: metrics_distributed_fit {}
INFO flwr 2024-07-11 12:53:13,883 | app.py:227 | app_fit: metrics_distributed {}
INFO flwr 2024-07-11 12:53:13,883 | app.py:228 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.42218090716583806), (2, 0.42459381430064413), (3, 0.42459537144356635), (4, 0.42764342270179195), (5, 0.4276294975432371), (6, 0.4300362567940795), (7, 0.43006175440224886), (8, 0.43006120592976305), (9, 0.42923387396620477), (10, 0.42923178480092666)]
INFO flwr 2024-07-11 12:53:13,884 | app.py:229 | app_fit: metrics_centralized {'accuracy': [(0, 0.4166666666666667), (1, 0.7866666666666666), (2, 0.7766666666666666), (3, 0.7766666666666666), (4, 0.79), (5, 0.79), (6, 0.7933333333333333), (7, 0.7933333333333333), (8, 0.7933333333333333), (9, 0.78), (10, 0.78)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-1.85667708,  0.749595  ,  0.80503962,  0.32744844,  0.2483238 ,
         0.09143037, -0.03827071,  0.04672176]]), array([0.17510058])]
[array([[-1.95853977,  0.90448507,  0.84658056,  0.39929962,  0.24822524,
         0.10000472, -0.00730879,  0.0442297 ]]), array([-0.06328627])]
[array([[-1.95807798,  0.90434669,  0.84637409,  0.39921207,  0.24823833,
         0.10002588, -0.00733247,  0.04420993]]), array([-0.06340446])]
[array([[-2.02892919,  0.95162068,  0.82365163,  0.4371235 ,  0.19627879,
         0.13506331, -0.03606715,  0.02833267]]), array([-0.00372767])]
[array([[-2.02889062,  0.95161668,  0.82357682,  0.43691289,  0.1960071 ,
         0.13491113, -0.03635528,  0.02824021]]), array([-0.002518])]
[array([[-2.01919071,  0.96678108,  0.81011007,  0.48162285,  0.20031177,
         0.12360088, -0.02264809,  0.00869408]]), array([-0.06060038])]
[array([[-2.01925543,  0.96738972,  0.81055684,  0.48207137,  0.20066895,
         0.12395071, -0.02220486,  0.00915191]]), array([-0.06372543])]
[array([[-2.01921272,  0.96741475,  0.81056201,  0.48205678,  0.20064651,
         0.12395613, -0.02216264,  0.00920912]]), array([-0.06385432])]
[array([[-1.99162263,  0.98090751,  0.80521795,  0.4528288 ,  0.20680917,
         0.10932782, -0.00677078,  0.03497839]]), array([-0.10084983])]
[array([[-1.9912055 ,  0.98032574,  0.80511831,  0.45282302,  0.2068389 ,
         0.10917984, -0.00660364,  0.03477973]]), array([-0.10092338])]
>>>>>>>>>>>>>run time:
0.640625s
