2023-09-18 18:05:30.934797: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:05:30.934960: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:05:38,481 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:05:38,548 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:05:38,548 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:05:38,548 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:05:39,467 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:05:39,467 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:39,483 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4166666666666667}
INFO flwr 2023-09-18 18:05:39,483 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:05:39,757 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:05:39,781 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:05:39,784 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:39,792 | server.py:125 | fit progress: (1, 0.42218090716583806, {'accuracy': 0.7866666666666666}, 0.3076767)
DEBUG flwr 2023-09-18 18:05:39,792 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:05:39,814 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:05:39,814 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:05:39,814 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:05:39,833 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:39,843 | server.py:125 | fit progress: (2, 0.42459381430064413, {'accuracy': 0.7766666666666666}, 0.35847109999999915)
DEBUG flwr 2023-09-18 18:05:39,843 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:05:39,861 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:05:39,861 | server.py:223 | fit_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 18:05:39,889 | server.py:237 | fit_round 3 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:39,899 | server.py:125 | fit progress: (3, 0.42922662837241804, {'accuracy': 0.7866666666666666}, 0.41485899999999987)
DEBUG flwr 2023-09-18 18:05:39,900 | server.py:173 | evaluate_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 18:05:39,923 | server.py:187 | evaluate_round 3 received 4 results and 0 failures
DEBUG flwr 2023-09-18 18:05:39,924 | server.py:223 | fit_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:05:39,956 | server.py:237 | fit_round 4 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:39,972 | server.py:125 | fit progress: (4, 0.43004835143979164, {'accuracy': 0.7933333333333333}, 0.4879938999999993)
DEBUG flwr 2023-09-18 18:05:39,972 | server.py:173 | evaluate_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:05:39,999 | server.py:187 | evaluate_round 4 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:05:39,999 | server.py:223 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:05:40,031 | server.py:237 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:40,043 | server.py:125 | fit progress: (5, 0.4300651083709704, {'accuracy': 0.7933333333333333}, 0.5586033999999991)
DEBUG flwr 2023-09-18 18:05:40,043 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:05:40,069 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:05:40,070 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:05:40,106 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:40,118 | server.py:125 | fit progress: (6, 0.43006149263251187, {'accuracy': 0.7933333333333333}, 0.6338615000000001)
DEBUG flwr 2023-09-18 18:05:40,118 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:05:40,143 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:05:40,144 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:05:40,172 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:40,183 | server.py:125 | fit progress: (7, 0.4300611026621741, {'accuracy': 0.7933333333333333}, 0.6990818000000001)
DEBUG flwr 2023-09-18 18:05:40,183 | server.py:173 | evaluate_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:05:40,208 | server.py:187 | evaluate_round 7 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:05:40,208 | server.py:223 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:05:40,243 | server.py:237 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:40,256 | server.py:125 | fit progress: (8, 0.42923386983739137, {'accuracy': 0.78}, 0.7719974000000001)
DEBUG flwr 2023-09-18 18:05:40,256 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:05:40,284 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:05:40,285 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:05:40,319 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:40,332 | server.py:125 | fit progress: (9, 0.429231785151516, {'accuracy': 0.78}, 0.8477240999999989)
DEBUG flwr 2023-09-18 18:05:40,332 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:05:40,362 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:05:40,363 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:05:40,395 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:05:40,408 | server.py:125 | fit progress: (10, 0.4292319517385956, {'accuracy': 0.78}, 0.9233481999999995)
DEBUG flwr 2023-09-18 18:05:40,408 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:05:40,434 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:05:40,435 | server.py:147 | FL finished in 0.950929799999999
INFO flwr 2023-09-18 18:05:40,435 | app.py:218 | app_fit: losses_distributed [(1, 0.41895109973847866), (2, 0.4162928145378828), (3, 0.4105220873441015), (4, 0.4054436449493681), (5, 0.40544212857882184), (6, 0.40544241950625465), (7, 0.40710226339953287), (8, 0.40697052436215536), (9, 0.4069710297243936), (10, 0.4069709522383554)]
INFO flwr 2023-09-18 18:05:40,435 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:05:40,435 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:05:40,435 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.42218090716583806), (2, 0.42459381430064413), (3, 0.42922662837241804), (4, 0.43004835143979164), (5, 0.4300651083709704), (6, 0.43006149263251187), (7, 0.4300611026621741), (8, 0.42923386983739137), (9, 0.429231785151516), (10, 0.4292319517385956)]
INFO flwr 2023-09-18 18:05:40,435 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.4166666666666667), (1, 0.7866666666666666), (2, 0.7766666666666666), (3, 0.7866666666666666), (4, 0.7933333333333333), (5, 0.7933333333333333), (6, 0.7933333333333333), (7, 0.7933333333333333), (8, 0.78), (9, 0.78), (10, 0.78)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-1.85667708,  0.749595  ,  0.80503962,  0.32744844,  0.2483238 ,
         0.09143037, -0.03827071,  0.04672176]]), array([0.17510058])]
[array([[-1.95853977,  0.90448507,  0.84658056,  0.39929962,  0.24822524,
         0.10000472, -0.00730879,  0.0442297 ]]), array([-0.06328627])]
[array([[-1.97367786e+00,  9.47301371e-01,  8.16353037e-01,
         4.82397199e-01,  2.32315737e-01,  9.80128816e-02,
         8.07807577e-04,  8.03983904e-03]]), array([-0.12454668])]
[array([[-2.01867656,  0.96631846,  0.81017092,  0.48176754,  0.20055038,
         0.12356504, -0.02215423,  0.00893025]]), array([-0.06258122])]
[array([[-2.01934581,  0.96735369,  0.81052641,  0.48213622,  0.20069749,
         0.12395707, -0.02231155,  0.00902839]]), array([-0.06345613])]
[array([[-2.01922076,  0.96741117,  0.81056069,  0.482063  ,  0.20065284,
         0.12395757, -0.02217614,  0.00919476]]), array([-0.06383029])]
[array([[-2.01920919,  0.96741572,  0.8105623 ,  0.48205433,  0.20064381,
         0.12395579, -0.02215726,  0.00921492]]), array([-0.06386412])]
[array([[-1.99162246,  0.98090756,  0.80521796,  0.45282865,  0.20680901,
         0.10932778, -0.00677047,  0.03497871]]), array([-0.1008503])]
[array([[-1.99120548,  0.98032572,  0.80511828,  0.452823  ,  0.20683891,
         0.10917984, -0.00660366,  0.03477976]]), array([-0.10092339])]
[array([[-1.99123722,  0.98037787,  0.80518169,  0.45287469,  0.20683558,
         0.10919725, -0.00655374,  0.03472796]]), array([-0.10100953])]
>>>>>>>>>>>>>run time:
0.375s
