2024-07-11 12:53:41.031452: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2024-07-11 12:53:41.031632: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2024-07-11 12:53:50,013 | app.py:165 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2024-07-11 12:53:50,103 | app.py:179 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2024-07-11 12:53:50,103 | server.py:89 | Initializing global parameters
INFO flwr 2024-07-11 12:53:50,103 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2024-07-11 12:53:51,308 | server.py:280 | Received initial parameters from one random client
INFO flwr 2024-07-11 12:53:51,308 | server.py:91 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:51,328 | server.py:98 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4266666666666667}
INFO flwr 2024-07-11 12:53:51,328 | server.py:104 | FL starting
DEBUG flwr 2024-07-11 12:53:51,595 | server.py:227 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,623 | server.py:241 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2024-07-11 12:53:51,625 | fedavgm.py:198 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:51,633 | server.py:131 | fit progress: (1, 0.43498346975410734, {'accuracy': 0.7966666666666666}, 0.3041862000000002)
DEBUG flwr 2024-07-11 12:53:51,633 | server.py:178 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,659 | server.py:192 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2024-07-11 12:53:51,659 | fedavg.py:273 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2024-07-11 12:53:51,660 | server.py:227 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,685 | server.py:241 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:51,696 | server.py:131 | fit progress: (2, 0.43648374892037406, {'accuracy': 0.8033333333333333}, 0.36662570000000017)
DEBUG flwr 2024-07-11 12:53:51,696 | server.py:178 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,718 | server.py:192 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:53:51,718 | server.py:227 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,740 | server.py:241 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:51,751 | server.py:131 | fit progress: (3, 0.4364738336634041, {'accuracy': 0.8033333333333333}, 0.42250109999999985)
DEBUG flwr 2024-07-11 12:53:51,751 | server.py:178 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,782 | server.py:192 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:53:51,782 | server.py:227 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,805 | server.py:241 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:51,816 | server.py:131 | fit progress: (4, 0.43647984505496784, {'accuracy': 0.8033333333333333}, 0.48760979999999954)
DEBUG flwr 2024-07-11 12:53:51,817 | server.py:178 | evaluate_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,840 | server.py:192 | evaluate_round 4 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:53:51,841 | server.py:227 | fit_round 5: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,882 | server.py:241 | fit_round 5 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:51,892 | server.py:131 | fit progress: (5, 0.43647635162316334, {'accuracy': 0.8033333333333333}, 0.5632827999999996)
DEBUG flwr 2024-07-11 12:53:51,893 | server.py:178 | evaluate_round 5: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:53:51,913 | server.py:192 | evaluate_round 5 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:53:51,914 | server.py:227 | fit_round 6: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:53:51,953 | server.py:241 | fit_round 6 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:51,965 | server.py:131 | fit progress: (6, 0.43538189735339566, {'accuracy': 0.79}, 0.6361986000000002)
DEBUG flwr 2024-07-11 12:53:51,966 | server.py:178 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,002 | server.py:192 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:53:52,003 | server.py:227 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,037 | server.py:241 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:52,049 | server.py:131 | fit progress: (7, 0.4349669878884359, {'accuracy': 0.79}, 0.7206157999999991)
DEBUG flwr 2024-07-11 12:53:52,050 | server.py:178 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,082 | server.py:192 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:53:52,083 | server.py:227 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,129 | server.py:241 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:52,141 | server.py:131 | fit progress: (8, 0.4349711068199506, {'accuracy': 0.79}, 0.8119336999999991)
DEBUG flwr 2024-07-11 12:53:52,141 | server.py:178 | evaluate_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,177 | server.py:192 | evaluate_round 8 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:53:52,177 | server.py:227 | fit_round 9: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,217 | server.py:241 | fit_round 9 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:52,229 | server.py:131 | fit progress: (9, 0.4349712715289382, {'accuracy': 0.79}, 0.9010877999999991)
DEBUG flwr 2024-07-11 12:53:52,230 | server.py:178 | evaluate_round 9: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,258 | server.py:192 | evaluate_round 9 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:53:52,258 | server.py:227 | fit_round 10: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,300 | server.py:241 | fit_round 10 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:53:52,312 | server.py:131 | fit progress: (10, 0.4349712874302742, {'accuracy': 0.79}, 0.9836572999999991)
DEBUG flwr 2024-07-11 12:53:52,313 | server.py:178 | evaluate_round 10: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:53:52,359 | server.py:192 | evaluate_round 10 received 5 results and 0 failures
INFO flwr 2024-07-11 12:53:52,359 | server.py:153 | FL finished in 1.030214299999999
INFO flwr 2024-07-11 12:53:52,359 | app.py:225 | app_fit: losses_distributed [(1, 0.3981874790042639), (2, 0.3965085092931986), (3, 0.39651142060756683), (4, 0.39650914818048477), (5, 0.39651094004511833), (6, 0.3954372696933292), (7, 0.39483143105393365), (8, 0.3948314856915247), (9, 0.39483152400879634), (10, 0.3948315367812202)]
INFO flwr 2024-07-11 12:53:52,360 | app.py:226 | app_fit: metrics_distributed_fit {}
INFO flwr 2024-07-11 12:53:52,360 | app.py:227 | app_fit: metrics_distributed {}
INFO flwr 2024-07-11 12:53:52,360 | app.py:228 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.43498346975410734), (2, 0.43648374892037406), (3, 0.4364738336634041), (4, 0.43647984505496784), (5, 0.43647635162316334), (6, 0.43538189735339566), (7, 0.4349669878884359), (8, 0.4349711068199506), (9, 0.4349712715289382), (10, 0.4349712874302742)]
INFO flwr 2024-07-11 12:53:52,360 | app.py:229 | app_fit: metrics_centralized {'accuracy': [(0, 0.4266666666666667), (1, 0.7966666666666666), (2, 0.8033333333333333), (3, 0.8033333333333333), (4, 0.8033333333333333), (5, 0.8033333333333333), (6, 0.79), (7, 0.79), (8, 0.79), (9, 0.79), (10, 0.79)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-1.95551526,  1.01039734,  0.75986324,  0.38731111,  0.29043523,
         0.21019872,  0.04117056,  0.00467682]]), array([-0.22705718])]
[array([[-2.01178822,  1.11985847,  0.80504283,  0.34380496,  0.249494  ,
         0.13213491,  0.00587767, -0.02946434]]), array([-0.03579957])]
[array([[-2.01105665,  1.11955041,  0.8046617 ,  0.34346004,  0.24916331,
         0.13187082,  0.00571978, -0.02935218]]), array([-0.03514952])]
[array([[-2.01165009,  1.11973204,  0.80495937,  0.34373347,  0.24933199,
         0.13211276,  0.00583752, -0.02944309]]), array([-0.03554647])]
[array([[-2.0112081 ,  1.11960819,  0.80471944,  0.34347134,  0.24923535,
         0.13191036,  0.00571309, -0.02937942]]), array([-0.03514473])]
[array([[-2.02559842,  1.09190181,  0.81753443,  0.36659956,  0.20281075,
         0.14361469,  0.08608457,  0.01149596]]), array([-0.17026893])]
[array([[-2.05237503,  1.13586856,  0.78219786,  0.40661076,  0.19229879,
         0.20319415,  0.07968129,  0.01924112]]), array([-0.22501737])]
[array([[-2.05234315,  1.13586074,  0.78219612,  0.40659282,  0.19229054,
         0.20324372,  0.07977622,  0.01919716]]), array([-0.22513225])]
[array([[-2.05232603,  1.1358524 ,  0.78219407,  0.40658175,  0.19227549,
         0.203246  ,  0.07978005,  0.01919772]]), array([-0.22512171])]
[array([[-2.05232166,  1.13585085,  0.78219236,  0.40657904,  0.19227308,
         0.20324627,  0.07978067,  0.01919802]]), array([-0.2251194])]
>>>>>>>>>>>>>run time:
0.46875s
