2023-09-18 18:06:07.610603: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:06:07.610773: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:06:15,142 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:06:15,209 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:06:15,210 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:06:15,210 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:06:16,168 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:06:16,168 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,183 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4266666666666667}
INFO flwr 2023-09-18 18:06:16,183 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:06:16,423 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:16,455 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:06:16,457 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,465 | server.py:125 | fit progress: (1, 0.43498346975410734, {'accuracy': 0.7966666666666666}, 0.28080560000000077)
DEBUG flwr 2023-09-18 18:06:16,465 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:16,490 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:06:16,490 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:06:16,490 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:16,511 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,523 | server.py:125 | fit progress: (2, 0.43648374892037406, {'accuracy': 0.8033333333333333}, 0.3384733999999998)
DEBUG flwr 2023-09-18 18:06:16,523 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:16,543 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:06:16,543 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:16,562 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,571 | server.py:125 | fit progress: (3, 0.43647383366340403, {'accuracy': 0.8033333333333333}, 0.38709990000000083)
DEBUG flwr 2023-09-18 18:06:16,572 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:16,588 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:06:16,589 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:06:16,609 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,619 | server.py:125 | fit progress: (4, 0.4364798450549677, {'accuracy': 0.8033333333333333}, 0.4350739000000008)
DEBUG flwr 2023-09-18 18:06:16,619 | server.py:173 | evaluate_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 18:06:16,642 | server.py:187 | evaluate_round 4 received 4 results and 0 failures
DEBUG flwr 2023-09-18 18:06:16,642 | server.py:223 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:16,677 | server.py:237 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,687 | server.py:125 | fit progress: (5, 0.43496555543104876, {'accuracy': 0.79}, 0.5036909999999999)
DEBUG flwr 2023-09-18 18:06:16,688 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:16,716 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:06:16,716 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:16,752 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,763 | server.py:125 | fit progress: (6, 0.4349706215234488, {'accuracy': 0.79}, 0.5785346000000011)
DEBUG flwr 2023-09-18 18:06:16,763 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:06:16,789 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:06:16,789 | server.py:223 | fit_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:16,833 | server.py:237 | fit_round 7 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,846 | server.py:125 | fit progress: (7, 0.4332402608105275, {'accuracy': 0.8}, 0.6618367000000003)
DEBUG flwr 2023-09-18 18:06:16,847 | server.py:173 | evaluate_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:16,879 | server.py:187 | evaluate_round 7 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:06:16,879 | server.py:223 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:16,916 | server.py:237 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:16,928 | server.py:125 | fit progress: (8, 0.43320722853159643, {'accuracy': 0.8}, 0.7443182999999998)
DEBUG flwr 2023-09-18 18:06:16,928 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:16,957 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:06:16,957 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:16,994 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:17,006 | server.py:125 | fit progress: (9, 0.4332100214908506, {'accuracy': 0.8}, 0.8221766000000006)
DEBUG flwr 2023-09-18 18:06:17,007 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:17,032 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:06:17,032 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:17,071 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:06:17,082 | server.py:125 | fit progress: (10, 0.433209594324508, {'accuracy': 0.8}, 0.897695800000001)
DEBUG flwr 2023-09-18 18:06:17,082 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:06:17,104 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:06:17,104 | server.py:147 | FL finished in 0.9203501000000003
INFO flwr 2023-09-18 18:06:17,104 | app.py:218 | app_fit: losses_distributed [(1, 0.3981874790042639), (2, 0.3965085092931986), (3, 0.39651142060756683), (4, 0.3998822192351023), (5, 0.394831983816056), (6, 0.3948315034310023), (7, 0.40079667355333054), (8, 0.40079421784196584), (9, 0.4007950076035091), (10, 0.4007949467216219)]
INFO flwr 2023-09-18 18:06:17,104 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:06:17,104 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:06:17,104 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.43498346975410734), (2, 0.43648374892037406), (3, 0.43647383366340403), (4, 0.4364798450549677), (5, 0.43496555543104876), (6, 0.4349706215234488), (7, 0.4332402608105275), (8, 0.43320722853159643), (9, 0.4332100214908506), (10, 0.433209594324508)]
INFO flwr 2023-09-18 18:06:17,105 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.4266666666666667), (1, 0.7966666666666666), (2, 0.8033333333333333), (3, 0.8033333333333333), (4, 0.8033333333333333), (5, 0.79), (6, 0.79), (7, 0.8), (8, 0.8), (9, 0.8), (10, 0.8)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-1.95551526,  1.01039734,  0.75986324,  0.38731111,  0.29043523,
         0.21019872,  0.04117056,  0.00467682]]), array([-0.22705718])]
[array([[-2.01178822,  1.11985847,  0.80504283,  0.34380496,  0.249494  ,
         0.13213491,  0.00587767, -0.02946434]]), array([-0.03579957])]
[array([[-2.01105665,  1.11955041,  0.8046617 ,  0.34346004,  0.24916331,
         0.13187082,  0.00571978, -0.02935218]]), array([-0.03514952])]
[array([[-2.01165009,  1.11973204,  0.80495937,  0.34373347,  0.24933199,
         0.13211276,  0.00583752, -0.02944309]]), array([-0.03554647])]
[array([[-2.05217263,  1.13581049,  0.78208478,  0.40647564,  0.192223  ,
         0.20313442,  0.07966376,  0.01925745]]), array([-0.22484263])]
[array([[-2.05233577,  1.13584425,  0.78218688,  0.40659481,  0.19229512,
         0.20324527,  0.0797715 ,  0.01919954]]), array([-0.22511407])]
[array([[-2.0412866 ,  1.0795197 ,  0.7422191 ,  0.39548196,  0.18348005,
         0.15530361,  0.01882653,  0.00499111]]), array([-0.04510551])]
[array([[-2.04291282,  1.08001433,  0.74234392,  0.39635721,  0.18409179,
         0.15491748,  0.01795076,  0.00507444]]), array([-0.04304201])]
[array([[-2.0422119 ,  1.0797299 ,  0.74220217,  0.39611785,  0.1839632 ,
         0.15497636,  0.01809206,  0.00512695]]), array([-0.04353319])]
[array([[-2.04226703,  1.07975029,  0.74220786,  0.39613997,  0.18397828,
         0.15497263,  0.01807868,  0.00512465]]), array([-0.04349309])]
>>>>>>>>>>>>>run time:
0.5625s
