2023-09-18 17:47:23.085516: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 17:47:23.085745: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 17:47:30,971 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 17:47:31,047 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 17:47:31,048 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 17:47:31,048 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 17:47:31,171 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 17:47:31,171 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:31,188 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.47333333333333333}
INFO flwr 2023-09-18 17:47:31,188 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 17:47:31,514 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 17:47:31,538 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 17:47:31,540 | fedavg.py:243 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:31,548 | server.py:125 | fit progress: (1, 0.3963137664597562, {'accuracy': 0.8233333333333334}, 0.35878229999999967)
DEBUG flwr 2023-09-18 17:47:31,548 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:47:31,575 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 17:47:31,576 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 17:47:31,576 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:47:31,597 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:31,609 | server.py:125 | fit progress: (2, 0.4019393582731748, {'accuracy': 0.84}, 0.42079689999999914)
DEBUG flwr 2023-09-18 17:47:31,609 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:47:31,628 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 17:47:31,628 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:47:31,653 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:31,667 | server.py:125 | fit progress: (3, 0.40193654239874566, {'accuracy': 0.84}, 0.47908189999999884)
DEBUG flwr 2023-09-18 17:47:31,669 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:47:31,696 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 17:47:31,697 | server.py:223 | fit_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:47:31,737 | server.py:237 | fit_round 4 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:31,749 | server.py:125 | fit progress: (4, 0.403996166878184, {'accuracy': 0.8333333333333334}, 0.5602890999999985)
DEBUG flwr 2023-09-18 17:47:31,749 | server.py:173 | evaluate_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:47:31,780 | server.py:187 | evaluate_round 4 received 4 results and 0 failures
DEBUG flwr 2023-09-18 17:47:31,781 | server.py:223 | fit_round 5: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:47:31,819 | server.py:237 | fit_round 5 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:31,831 | server.py:125 | fit progress: (5, 0.40399697720674366, {'accuracy': 0.8333333333333334}, 0.6434566999999998)
DEBUG flwr 2023-09-18 17:47:31,832 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:47:31,863 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:47:31,864 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:47:31,900 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:31,912 | server.py:125 | fit progress: (6, 0.4073266956319031, {'accuracy': 0.8366666666666667}, 0.7236256000000001)
DEBUG flwr 2023-09-18 17:47:31,912 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:47:31,956 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:47:31,956 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:47:31,996 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:32,008 | server.py:125 | fit progress: (7, 0.40732702672439963, {'accuracy': 0.8366666666666667}, 0.819509)
DEBUG flwr 2023-09-18 17:47:32,009 | server.py:173 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:47:32,034 | server.py:187 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:47:32,035 | server.py:223 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:47:32,087 | server.py:237 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:32,100 | server.py:125 | fit progress: (8, 0.41018449107327926, {'accuracy': 0.83}, 0.9120197999999995)
DEBUG flwr 2023-09-18 17:47:32,101 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:47:32,134 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:47:32,134 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:47:32,180 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:32,193 | server.py:125 | fit progress: (9, 0.4101837360613022, {'accuracy': 0.83}, 1.0046228)
DEBUG flwr 2023-09-18 17:47:32,194 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:47:32,246 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:47:32,247 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:47:32,297 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:47:32,311 | server.py:125 | fit progress: (10, 0.41018372418874655, {'accuracy': 0.83}, 1.122535899999999)
DEBUG flwr 2023-09-18 17:47:32,311 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:47:32,382 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 17:47:32,382 | server.py:147 | FL finished in 1.1943706999999986
INFO flwr 2023-09-18 17:47:32,383 | app.py:218 | app_fit: losses_distributed [(1, 0.39909929409623146), (2, 0.39741609059274197), (3, 0.39741579443216324), (4, 0.3994787111878395), (5, 0.41198169262636275), (6, 0.41175217287881033), (7, 0.41175225093251183), (8, 0.4149142499480929), (9, 0.41491421588829586), (10, 0.4149142209972654)]
INFO flwr 2023-09-18 17:47:32,383 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 17:47:32,383 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 17:47:32,383 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.3963137664597562), (2, 0.4019393582731748), (3, 0.40193654239874566), (4, 0.403996166878184), (5, 0.40399697720674366), (6, 0.4073266956319031), (7, 0.40732702672439963), (8, 0.41018449107327926), (9, 0.4101837360613022), (10, 0.41018372418874655)]
INFO flwr 2023-09-18 17:47:32,383 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.47333333333333333), (1, 0.8233333333333334), (2, 0.84), (3, 0.84), (4, 0.8333333333333334), (5, 0.8333333333333334), (6, 0.8366666666666667), (7, 0.8366666666666667), (8, 0.83), (9, 0.83), (10, 0.83)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
>>>>>>>>>>>>> evaluating on server-side
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.00895377,  1.13981466,  0.83036406,  0.30825985,  0.30118098,
         0.13342745,  0.02561959, -0.17047549]]), array([-0.12612808])]
[array([[-2.00895377,  1.13981466,  0.83036406,  0.30825985,  0.30118098,
         0.13342745,  0.02561959, -0.17047549]]), array([-0.12612808])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.94751619,  1.08416535,  0.82737041,  0.39050045,  0.26057978,
         0.05010871, -0.03325109, -0.09733011]]), array([-0.03772277])]
[array([[-1.94751619,  1.08416535,  0.82737041,  0.39050045,  0.26057978,
         0.05010871, -0.03325109, -0.09733011]]), array([-0.03772277])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.94754403,  1.0841863 ,  0.82750718,  0.39054288,  0.26062749,
         0.05008643, -0.03321814, -0.09751476]]), array([-0.03773237])]
[array([[-1.94754403,  1.0841863 ,  0.82750718,  0.39054288,  0.26062749,
         0.05008643, -0.03321814, -0.09751476]]), array([-0.03773237])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.01534363,  1.03090696,  0.84906095,  0.31173063,  0.19613011,
         0.06417727,  0.03410287, -0.07479409]]), array([0.03124479])]
[array([[-2.01534363,  1.03090696,  0.84906095,  0.31173063,  0.19613011,
         0.06417727,  0.03410287, -0.07479409]]), array([0.03124479])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.0154264 ,  1.03097384,  0.84906823,  0.31174388,  0.19611183,
         0.06415688,  0.03410979, -0.07476014]]), array([0.03123486])]
[array([[-2.0154264 ,  1.03097384,  0.84906823,  0.31174388,  0.19611183,
         0.06415688,  0.03410979, -0.07476014]]), array([0.03123486])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.95926702,  0.96557987,  0.82253357,  0.31634917,  0.19760549,
         0.04844156,  0.03757076, -0.04191387]]), array([0.05175803])]
[array([[-1.95926702,  0.96557987,  0.82253357,  0.31634917,  0.19760549,
         0.04844156,  0.03757076, -0.04191387]]), array([0.05175803])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.95926102,  0.96558166,  0.82240821,  0.31632328,  0.19753679,
         0.04845081,  0.03752701, -0.0419105 ]]), array([0.05201409])]
[array([[-1.95926102,  0.96558166,  0.82240821,  0.31632328,  0.19753679,
         0.04845081,  0.03752701, -0.0419105 ]]), array([0.05201409])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.94091432,  0.93747167,  0.80679377,  0.32163781,  0.18347821,
         0.01510495,  0.03405536, -0.0473341 ]]), array([0.14855729])]
[array([[-1.94091432,  0.93747167,  0.80679377,  0.32163781,  0.18347821,
         0.01510495,  0.03405536, -0.0473341 ]]), array([0.14855729])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.94093648,  0.93744875,  0.80685139,  0.32168351,  0.18353195,
         0.01507338,  0.03398903, -0.04735351]]), array([0.14857135])]
[array([[-1.94093648,  0.93744875,  0.80685139,  0.32168351,  0.18353195,
         0.01507338,  0.03398903, -0.04735351]]), array([0.14857135])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.94093643,  0.9374488 ,  0.8068514 ,  0.32168365,  0.18353197,
         0.01507351,  0.03398884, -0.04735352]]), array([0.1485712])]
[array([[-1.94093643,  0.9374488 ,  0.8068514 ,  0.32168365,  0.18353197,
         0.01507351,  0.03398884, -0.04735352]]), array([0.1485712])]
>>>>>>>>>>>>>run time:
0.5s
