2023-09-18 17:41:11.772065: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 17:41:11.772232: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 17:41:19,341 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 17:41:19,411 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 17:41:19,412 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 17:41:19,412 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 17:41:19,416 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 17:41:19,416 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:19,432 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4166666666666667}
INFO flwr 2023-09-18 17:41:19,433 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 17:41:19,633 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 17:41:19,656 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 17:41:19,661 | fedavg.py:243 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:19,673 | server.py:125 | fit progress: (1, 0.3587717529432016, {'accuracy': 0.8566666666666667}, 0.24054779999999987)
DEBUG flwr 2023-09-18 17:41:19,674 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:41:19,700 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 17:41:19,700 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 17:41:19,701 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:41:19,724 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:19,737 | server.py:125 | fit progress: (2, 0.36232605492519615, {'accuracy': 0.85}, 0.3037092000000001)
DEBUG flwr 2023-09-18 17:41:19,737 | server.py:173 | evaluate_round 2: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:41:19,759 | server.py:187 | evaluate_round 2 received 4 results and 0 failures
DEBUG flwr 2023-09-18 17:41:19,759 | server.py:223 | fit_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:41:19,790 | server.py:237 | fit_round 3 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:19,802 | server.py:125 | fit progress: (3, 0.3633740852550543, {'accuracy': 0.8533333333333334}, 0.3687486999999994)
DEBUG flwr 2023-09-18 17:41:19,802 | server.py:173 | evaluate_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:41:19,825 | server.py:187 | evaluate_round 3 received 4 results and 0 failures
DEBUG flwr 2023-09-18 17:41:19,825 | server.py:223 | fit_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:41:19,855 | server.py:237 | fit_round 4 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:19,866 | server.py:125 | fit progress: (4, 0.36337537321905, {'accuracy': 0.8533333333333334}, 0.43376839999999994)
DEBUG flwr 2023-09-18 17:41:19,867 | server.py:173 | evaluate_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:41:19,893 | server.py:187 | evaluate_round 4 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:41:19,893 | server.py:223 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:41:19,931 | server.py:237 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:19,943 | server.py:125 | fit progress: (5, 0.3695539232609121, {'accuracy': 0.8433333333333334}, 0.5098529000000003)
DEBUG flwr 2023-09-18 17:41:19,943 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:41:19,965 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:41:19,965 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:41:19,999 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:20,011 | server.py:125 | fit progress: (6, 0.3695529909431491, {'accuracy': 0.8433333333333334}, 0.5774153000000002)
DEBUG flwr 2023-09-18 17:41:20,011 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:41:20,039 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:41:20,039 | server.py:223 | fit_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:41:20,070 | server.py:237 | fit_round 7 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:20,082 | server.py:125 | fit progress: (7, 0.3708148374977868, {'accuracy': 0.84}, 0.6496732999999999)
DEBUG flwr 2023-09-18 17:41:20,082 | server.py:173 | evaluate_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:41:20,113 | server.py:187 | evaluate_round 7 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:41:20,113 | server.py:223 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:41:20,148 | server.py:237 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:20,162 | server.py:125 | fit progress: (8, 0.37081476193603174, {'accuracy': 0.84}, 0.7295286999999995)
DEBUG flwr 2023-09-18 17:41:20,163 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:41:20,191 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:41:20,191 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:41:20,228 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:20,241 | server.py:125 | fit progress: (9, 0.37081451382644415, {'accuracy': 0.84}, 0.8080732000000008)
DEBUG flwr 2023-09-18 17:41:20,242 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:41:20,271 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:41:20,272 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:41:20,306 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:41:20,318 | server.py:125 | fit progress: (10, 0.37081450652001774, {'accuracy': 0.84}, 0.8856526999999996)
DEBUG flwr 2023-09-18 17:41:20,319 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:41:20,352 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 17:41:20,352 | server.py:147 | FL finished in 0.9194353999999993
INFO flwr 2023-09-18 17:41:20,352 | app.py:218 | app_fit: losses_distributed [(1, 0.3797343199451764), (2, 0.38243415355682375), (3, 0.38196518222490944), (4, 0.39641535487668267), (5, 0.3947503541050286), (6, 0.3947497380190882), (7, 0.39690335733549936), (8, 0.39690414667129514), (9, 0.39690415007727486), (10, 0.39690414709704264)]
INFO flwr 2023-09-18 17:41:20,353 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 17:41:20,353 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 17:41:20,353 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.3587717529432016), (2, 0.36232605492519615), (3, 0.3633740852550543), (4, 0.36337537321905), (5, 0.3695539232609121), (6, 0.3695529909431491), (7, 0.3708148374977868), (8, 0.37081476193603174), (9, 0.37081451382644415), (10, 0.37081450652001774)]
INFO flwr 2023-09-18 17:41:20,353 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.4166666666666667), (1, 0.8566666666666667), (2, 0.85), (3, 0.8533333333333334), (4, 0.8533333333333334), (5, 0.8433333333333334), (6, 0.8433333333333334), (7, 0.84), (8, 0.84), (9, 0.84), (10, 0.84)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
>>>>>>>>>>>>> evaluating on server-side
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.13719726,  1.04788512,  1.03721415,  0.41621155,  0.27318453,
         0.05073418, -0.19907719,  0.20226837]]), array([-0.00915889])]
[array([[-2.13719726,  1.04788512,  1.03721415,  0.41621155,  0.27318453,
         0.05073418, -0.19907719,  0.20226837]]), array([-0.00915889])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.12597822,  1.05606685,  0.88014156,  0.33532097,  0.24308389,
         0.05586597, -0.1012149 ,  0.14034259]]), array([0.08838503])]
[array([[-2.12597822,  1.05606685,  0.88014156,  0.33532097,  0.24308389,
         0.05586597, -0.1012149 ,  0.14034259]]), array([0.08838503])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.09245569,  1.0746278 ,  0.86794077,  0.3755003 ,  0.22968431,
         0.08356021, -0.09743639,  0.08266974]]), array([0.03240118])]
[array([[-2.09245569,  1.0746278 ,  0.86794077,  0.3755003 ,  0.22968431,
         0.08356021, -0.09743639,  0.08266974]]), array([0.03240118])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.09242139,  1.0746722 ,  0.86790042,  0.37552545,  0.22956906,
         0.08360321, -0.09751231,  0.08267817]]), array([0.03246653])]
[array([[-2.09242139,  1.0746722 ,  0.86790042,  0.37552545,  0.22956906,
         0.08360321, -0.09751231,  0.08267817]]), array([0.03246653])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.0276402 ,  1.07531889,  0.77805186,  0.38632337,  0.20469615,
         0.13160617, -0.05441161, -0.02976845]]), array([0.07705673])]
[array([[-2.0276402 ,  1.07531889,  0.77805186,  0.38632337,  0.20469615,
         0.13160617, -0.05441161, -0.02976845]]), array([0.07705673])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.0280667 ,  1.07557043,  0.77809493,  0.38636687,  0.20472379,
         0.1316765 , -0.0543329 , -0.02980407]]), array([0.07708377])]
[array([[-2.0280667 ,  1.07557043,  0.77809493,  0.38636687,  0.20472379,
         0.1316765 , -0.0543329 , -0.02980407]]), array([0.07708377])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.02696274,  1.06973267,  0.75369674,  0.36787513,  0.1739652 ,
         0.13695927, -0.06528683, -0.02577675]]), array([0.16096181])]
[array([[-2.02696274,  1.06973267,  0.75369674,  0.36787513,  0.1739652 ,
         0.13695927, -0.06528683, -0.02577675]]), array([0.16096181])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.02642467,  1.0695264 ,  0.75363731,  0.36765944,  0.17388949,
         0.13691806, -0.06538537, -0.02561583]]), array([0.16080842])]
[array([[-2.02642467,  1.0695264 ,  0.75363731,  0.36765944,  0.17388949,
         0.13691806, -0.06538537, -0.02561583]]), array([0.16080842])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.0264239 ,  1.06952779,  0.75363674,  0.36766597,  0.17389009,
         0.13691619, -0.06538894, -0.02561351]]), array([0.16080243])]
[array([[-2.0264239 ,  1.06952779,  0.75363674,  0.36766597,  0.17389009,
         0.13691619, -0.06538894, -0.02561351]]), array([0.16080243])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-2.02642385,  1.06952778,  0.75363677,  0.36766605,  0.17389016,
         0.13691621, -0.06538899, -0.02561343]]), array([0.16080212])]
[array([[-2.02642385,  1.06952778,  0.75363677,  0.36766605,  0.17389016,
         0.13691621, -0.06538899, -0.02561343]]), array([0.16080212])]
>>>>>>>>>>>>>run time:
0.421875s
