2023-09-18 18:04:41.747517: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 18:04:41.747695: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 18:04:49,282 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 18:04:49,350 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 18:04:49,350 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 18:04:49,350 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 18:04:50,313 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 18:04:50,313 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:50,329 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4166666666666667}
INFO flwr 2023-09-18 18:04:50,329 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 18:04:50,605 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:50,641 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 18:04:50,643 | fedavgm.py:214 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:50,650 | server.py:125 | fit progress: (1, 0.36551106688592494, {'accuracy': 0.8466666666666667}, 0.3205366000000005)
DEBUG flwr 2023-09-18 18:04:50,650 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:50,676 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 18:04:50,677 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 18:04:50,677 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:50,698 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:50,707 | server.py:125 | fit progress: (2, 0.36158440417038884, {'accuracy': 0.8466666666666667}, 0.378483000000001)
DEBUG flwr 2023-09-18 18:04:50,708 | server.py:173 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:50,723 | server.py:187 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:04:50,723 | server.py:223 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:50,742 | server.py:237 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:50,752 | server.py:125 | fit progress: (3, 0.36158849685263483, {'accuracy': 0.8466666666666667}, 0.4227085000000006)
DEBUG flwr 2023-09-18 18:04:50,752 | server.py:173 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:50,771 | server.py:187 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2023-09-18 18:04:50,772 | server.py:223 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 18:04:50,790 | server.py:237 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:50,800 | server.py:125 | fit progress: (4, 0.3615884890430525, {'accuracy': 0.8466666666666667}, 0.470653200000001)
DEBUG flwr 2023-09-18 18:04:50,800 | server.py:173 | evaluate_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 18:04:50,822 | server.py:187 | evaluate_round 4 received 4 results and 0 failures
DEBUG flwr 2023-09-18 18:04:50,822 | server.py:223 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:50,851 | server.py:237 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:50,868 | server.py:125 | fit progress: (5, 0.36675023729891765, {'accuracy': 0.8433333333333334}, 0.5385904999999998)
DEBUG flwr 2023-09-18 18:04:50,868 | server.py:173 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:50,897 | server.py:187 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:04:50,898 | server.py:223 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:50,937 | server.py:237 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:50,949 | server.py:125 | fit progress: (6, 0.3667505237026685, {'accuracy': 0.8433333333333334}, 0.6199217000000008)
DEBUG flwr 2023-09-18 18:04:50,949 | server.py:173 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:50,975 | server.py:187 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-09-18 18:04:50,976 | server.py:223 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 18:04:51,006 | server.py:237 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:51,018 | server.py:125 | fit progress: (7, 0.3667505218384559, {'accuracy': 0.8433333333333334}, 0.6885094000000009)
DEBUG flwr 2023-09-18 18:04:51,018 | server.py:173 | evaluate_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:51,050 | server.py:187 | evaluate_round 7 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:04:51,051 | server.py:223 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:51,089 | server.py:237 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:51,102 | server.py:125 | fit progress: (8, 0.370814951238618, {'accuracy': 0.84}, 0.7721676000000013)
DEBUG flwr 2023-09-18 18:04:51,102 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:51,129 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:04:51,130 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:51,165 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:51,178 | server.py:125 | fit progress: (9, 0.3708144508554772, {'accuracy': 0.84}, 0.8487963000000001)
DEBUG flwr 2023-09-18 18:04:51,178 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:51,203 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 18:04:51,203 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:51,234 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 18:04:51,245 | server.py:125 | fit progress: (10, 0.3708145022839997, {'accuracy': 0.84}, 0.9161953)
DEBUG flwr 2023-09-18 18:04:51,246 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 18:04:51,272 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 18:04:51,272 | server.py:147 | FL finished in 0.9427295000000004
INFO flwr 2023-09-18 18:04:51,272 | app.py:218 | app_fit: losses_distributed [(1, 0.3793262764811516), (2, 0.37746201641857624), (3, 0.37746284902095795), (4, 0.39328061789274216), (5, 0.3896346234139942), (6, 0.38963460212662104), (7, 0.39774757368224006), (8, 0.39690379117216384), (9, 0.3969041496515274), (10, 0.39690414709704264)]
INFO flwr 2023-09-18 18:04:51,272 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 18:04:51,272 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 18:04:51,273 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.36551106688592494), (2, 0.36158440417038884), (3, 0.36158849685263483), (4, 0.3615884890430525), (5, 0.36675023729891765), (6, 0.3667505237026685), (7, 0.3667505218384559), (8, 0.370814951238618), (9, 0.3708144508554772), (10, 0.3708145022839997)]
INFO flwr 2023-09-18 18:04:51,273 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.4166666666666667), (1, 0.8466666666666667), (2, 0.8466666666666667), (3, 0.8466666666666667), (4, 0.8466666666666667), (5, 0.8433333333333334), (6, 0.8433333333333334), (7, 0.8433333333333334), (8, 0.84), (9, 0.84), (10, 0.84)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.00633273,  1.15108665,  0.8578269 ,  0.49911009,  0.22866519,
         0.15318118, -0.10433397, -0.00577136]]), array([-0.19709109])]
[array([[-2.07022049,  1.0859416 ,  0.95336522,  0.46071026,  0.23688522,
         0.10522237, -0.15704624,  0.07032036]]), array([-0.07484595])]
[array([[-2.07008172,  1.0858136 ,  0.9532837 ,  0.46070235,  0.23680858,
         0.10524984, -0.15701684,  0.07032012]]), array([-0.07482412])]
[array([[-2.07008191,  1.08581378,  0.95328407,  0.46070205,  0.23680869,
         0.10525031, -0.15701672,  0.07032032]]), array([-0.07482509])]
[array([[-2.07227833,  1.06528474,  0.80155181,  0.34787396,  0.17127653,
         0.10616755, -0.10338997,  0.05724658]]), array([0.18478321])]
[array([[-2.07224526,  1.06533521,  0.80164736,  0.34784242,  0.17118501,
         0.10617661, -0.10340768,  0.05721959]]), array([0.18479222])]
[array([[-2.07224325,  1.06533418,  0.80164668,  0.34784264,  0.17118249,
         0.10617339, -0.10340855,  0.05722113]]), array([0.18479677])]
[array([[-2.02662672,  1.0695977 ,  0.75370451,  0.36785713,  0.17393037,
         0.13691339, -0.06530883, -0.02575048]]), array([0.16076137])]
[array([[-2.02642368,  1.06952758,  0.75363855,  0.36766486,  0.17389097,
         0.13691715, -0.06538873, -0.02561309]]), array([0.16079958])]
[array([[-2.02642384,  1.06952779,  0.75363682,  0.36766609,  0.1738902 ,
         0.13691622, -0.06538902, -0.0256134 ]]), array([0.16080198])]
>>>>>>>>>>>>>run time:
0.5625s
