2024-07-11 12:52:12.426170: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2024-07-11 12:52:12.426352: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2024-07-11 12:52:21,833 | app.py:165 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2024-07-11 12:52:21,925 | app.py:179 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2024-07-11 12:52:21,925 | server.py:89 | Initializing global parameters
INFO flwr 2024-07-11 12:52:21,925 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2024-07-11 12:52:23,056 | server.py:280 | Received initial parameters from one random client
INFO flwr 2024-07-11 12:52:23,057 | server.py:91 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,075 | server.py:98 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.4166666666666667}
INFO flwr 2024-07-11 12:52:23,075 | server.py:104 | FL starting
DEBUG flwr 2024-07-11 12:52:23,285 | server.py:227 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,314 | server.py:241 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2024-07-11 12:52:23,316 | fedavgm.py:198 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,324 | server.py:131 | fit progress: (1, 0.3587717529432016, {'accuracy': 0.8566666666666667}, 0.24875179999999908)
DEBUG flwr 2024-07-11 12:52:23,324 | server.py:178 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,349 | server.py:192 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2024-07-11 12:52:23,350 | fedavg.py:273 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2024-07-11 12:52:23,350 | server.py:227 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,383 | server.py:241 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,395 | server.py:131 | fit progress: (2, 0.3623260549251961, {'accuracy': 0.85}, 0.31920159999999953)
DEBUG flwr 2024-07-11 12:52:23,395 | server.py:178 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,415 | server.py:192 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:52:23,416 | server.py:227 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,453 | server.py:241 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,465 | server.py:131 | fit progress: (3, 0.36232698204964153, {'accuracy': 0.85}, 0.3892624999999992)
DEBUG flwr 2024-07-11 12:52:23,466 | server.py:178 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,490 | server.py:192 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:52:23,491 | server.py:227 | fit_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,527 | server.py:241 | fit_round 4 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,538 | server.py:131 | fit progress: (4, 0.36232697144183906, {'accuracy': 0.85}, 0.4626462)
DEBUG flwr 2024-07-11 12:52:23,538 | server.py:178 | evaluate_round 4: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,560 | server.py:192 | evaluate_round 4 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:52:23,560 | server.py:227 | fit_round 5: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,593 | server.py:241 | fit_round 5 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,605 | server.py:131 | fit progress: (5, 0.362326971646484, {'accuracy': 0.85}, 0.5292092999999998)
DEBUG flwr 2024-07-11 12:52:23,605 | server.py:178 | evaluate_round 5: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,640 | server.py:192 | evaluate_round 5 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:52:23,640 | server.py:227 | fit_round 6: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:52:23,699 | server.py:241 | fit_round 6 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,709 | server.py:131 | fit progress: (6, 0.36232697164411387, {'accuracy': 0.85}, 0.6328388999999994)
DEBUG flwr 2024-07-11 12:52:23,709 | server.py:178 | evaluate_round 6: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:52:23,745 | server.py:192 | evaluate_round 6 received 4 results and 0 failures
DEBUG flwr 2024-07-11 12:52:23,746 | server.py:227 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:52:23,797 | server.py:241 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,809 | server.py:131 | fit progress: (7, 0.3695511419127125, {'accuracy': 0.8433333333333334}, 0.7332625000000004)
DEBUG flwr 2024-07-11 12:52:23,809 | server.py:178 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:52:23,842 | server.py:192 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:52:23,843 | server.py:227 | fit_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:52:23,907 | server.py:241 | fit_round 8 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:23,919 | server.py:131 | fit progress: (8, 0.36955297424402433, {'accuracy': 0.8433333333333334}, 0.8429935000000004)
DEBUG flwr 2024-07-11 12:52:23,919 | server.py:178 | evaluate_round 8: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:52:23,956 | server.py:192 | evaluate_round 8 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:52:23,956 | server.py:227 | fit_round 9: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:52:23,995 | server.py:241 | fit_round 9 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:24,007 | server.py:131 | fit progress: (9, 0.369552930268666, {'accuracy': 0.8433333333333334}, 0.9316534000000001)
DEBUG flwr 2024-07-11 12:52:24,007 | server.py:178 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:52:24,048 | server.py:192 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:52:24,048 | server.py:227 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:52:24,098 | server.py:241 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:52:24,110 | server.py:131 | fit progress: (10, 0.370814836299115, {'accuracy': 0.84}, 1.0346355999999997)
DEBUG flwr 2024-07-11 12:52:24,111 | server.py:178 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:52:24,139 | server.py:192 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2024-07-11 12:52:24,139 | server.py:153 | FL finished in 1.0636221999999993
INFO flwr 2024-07-11 12:52:24,140 | app.py:225 | app_fit: losses_distributed [(1, 0.3797343199451764), (2, 0.3770385608077049), (3, 0.37703843290607136), (4, 0.3770384242137273), (5, 0.3770384242137273), (6, 0.3976523234294011), (7, 0.3947502713778923), (8, 0.3947497400744208), (9, 0.3970163813659123), (10, 0.39690335733549936)]
INFO flwr 2024-07-11 12:52:24,140 | app.py:226 | app_fit: metrics_distributed_fit {}
INFO flwr 2024-07-11 12:52:24,140 | app.py:227 | app_fit: metrics_distributed {}
INFO flwr 2024-07-11 12:52:24,140 | app.py:228 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.3587717529432016), (2, 0.3623260549251961), (3, 0.36232698204964153), (4, 0.36232697144183906), (5, 0.362326971646484), (6, 0.36232697164411387), (7, 0.3695511419127125), (8, 0.36955297424402433), (9, 0.369552930268666), (10, 0.370814836299115)]
INFO flwr 2024-07-11 12:52:24,140 | app.py:229 | app_fit: metrics_centralized {'accuracy': [(0, 0.4166666666666667), (1, 0.8566666666666667), (2, 0.85), (3, 0.85), (4, 0.85), (5, 0.85), (6, 0.85), (7, 0.8433333333333334), (8, 0.8433333333333334), (9, 0.8433333333333334), (10, 0.84)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-2.13719726,  1.04788512,  1.03721415,  0.41621155,  0.27318453,
         0.05073418, -0.19907719,  0.20226837]]), array([-0.00915889])]
[array([[-2.12597822,  1.05606685,  0.88014156,  0.33532097,  0.24308389,
         0.05586597, -0.1012149 ,  0.14034259]]), array([0.08838503])]
[array([[-2.12599816,  1.05603716,  0.88018138,  0.33525781,  0.24313749,
         0.05583725, -0.10117491,  0.1402951 ]]), array([0.08846038])]
[array([[-2.12599827,  1.05603669,  0.88018156,  0.33525748,  0.24313842,
         0.05583675, -0.10117458,  0.1402955 ]]), array([0.08845995])]
[array([[-2.12599827,  1.05603669,  0.88018157,  0.33525748,  0.24313842,
         0.05583676, -0.10117458,  0.14029549]]), array([0.08845995])]
[array([[-2.12599827,  1.05603669,  0.88018157,  0.33525748,  0.24313842,
         0.05583676, -0.10117458,  0.14029549]]), array([0.08845995])]
[array([[-2.02769237,  1.07530277,  0.77810314,  0.38633028,  0.20477905,
         0.13160463, -0.0544186 , -0.02977404]]), array([0.07701553])]
[array([[-2.02806677,  1.07557012,  0.77809564,  0.386367  ,  0.20472411,
         0.13167726, -0.05433355, -0.0298041 ]]), array([0.07708288])]
[array([[-2.0280641 ,  1.07556862,  0.77809587,  0.38636673,  0.20472529,
         0.13167838, -0.05433523, -0.0298032 ]]), array([0.07707895])]
[array([[-2.02696268,  1.06973265,  0.75369675,  0.36787514,  0.17396518,
         0.13695921, -0.06528684, -0.02577674]]), array([0.16096183])]
>>>>>>>>>>>>>run time:
0.578125s
