2023-09-18 17:46:15.029241: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-09-18 17:46:15.029416: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2023-09-18 17:46:22,612 | app.py:151 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-09-18 17:46:22,690 | app.py:172 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-09-18 17:46:22,690 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-18 17:46:22,690 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2023-09-18 17:46:22,746 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-09-18 17:46:22,746 | server.py:88 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:22,763 | server.py:95 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.45}
INFO flwr 2023-09-18 17:46:22,763 | server.py:101 | FL starting
DEBUG flwr 2023-09-18 17:46:22,948 | server.py:223 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2023-09-18 17:46:22,977 | server.py:237 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2023-09-18 17:46:22,980 | fedavg.py:243 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:22,990 | server.py:125 | fit progress: (1, 0.42299553936553613, {'accuracy': 0.7933333333333333}, 0.22695370000000104)
DEBUG flwr 2023-09-18 17:46:22,990 | server.py:173 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:46:23,020 | server.py:187 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2023-09-18 17:46:23,021 | fedavg.py:274 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-09-18 17:46:23,021 | server.py:223 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2023-09-18 17:46:23,049 | server.py:237 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,061 | server.py:125 | fit progress: (2, 0.42318669485711913, {'accuracy': 0.7933333333333333}, 0.2978196999999998)
DEBUG flwr 2023-09-18 17:46:23,062 | server.py:173 | evaluate_round 2: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:46:23,084 | server.py:187 | evaluate_round 2 received 4 results and 0 failures
DEBUG flwr 2023-09-18 17:46:23,084 | server.py:223 | fit_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:46:23,110 | server.py:237 | fit_round 3 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,121 | server.py:125 | fit progress: (3, 0.4247167514939962, {'accuracy': 0.7866666666666666}, 0.3580047000000004)
DEBUG flwr 2023-09-18 17:46:23,121 | server.py:173 | evaluate_round 3: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:46:23,143 | server.py:187 | evaluate_round 3 received 4 results and 0 failures
DEBUG flwr 2023-09-18 17:46:23,143 | server.py:223 | fit_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2023-09-18 17:46:23,176 | server.py:237 | fit_round 4 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,186 | server.py:125 | fit progress: (4, 0.4247221972649737, {'accuracy': 0.7866666666666666}, 0.4233916000000004)
DEBUG flwr 2023-09-18 17:46:23,187 | server.py:173 | evaluate_round 4: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:46:23,213 | server.py:187 | evaluate_round 4 received 5 results and 0 failures
DEBUG flwr 2023-09-18 17:46:23,214 | server.py:223 | fit_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2023-09-18 17:46:23,240 | server.py:237 | fit_round 5 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,252 | server.py:125 | fit progress: (5, 0.4260933780833511, {'accuracy': 0.7933333333333333}, 0.48842939999999935)
DEBUG flwr 2023-09-18 17:46:23,252 | server.py:173 | evaluate_round 5: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,276 | server.py:187 | evaluate_round 5 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:46:23,277 | server.py:223 | fit_round 6: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,310 | server.py:237 | fit_round 6 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,321 | server.py:125 | fit progress: (6, 0.426980787211221, {'accuracy': 0.79}, 0.5580698000000002)
DEBUG flwr 2023-09-18 17:46:23,321 | server.py:173 | evaluate_round 6: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,349 | server.py:187 | evaluate_round 6 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:46:23,350 | server.py:223 | fit_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,381 | server.py:237 | fit_round 7 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,393 | server.py:125 | fit progress: (7, 0.42698765587527715, {'accuracy': 0.79}, 0.6301898999999995)
DEBUG flwr 2023-09-18 17:46:23,393 | server.py:173 | evaluate_round 7: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,421 | server.py:187 | evaluate_round 7 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:46:23,421 | server.py:223 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,453 | server.py:237 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,468 | server.py:125 | fit progress: (8, 0.42698456457471023, {'accuracy': 0.79}, 0.7047194000000001)
DEBUG flwr 2023-09-18 17:46:23,468 | server.py:173 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,496 | server.py:187 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:46:23,496 | server.py:223 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,537 | server.py:237 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,550 | server.py:125 | fit progress: (9, 0.42698525143596916, {'accuracy': 0.79}, 0.7860244000000005)
DEBUG flwr 2023-09-18 17:46:23,550 | server.py:173 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,578 | server.py:187 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2023-09-18 17:46:23,578 | server.py:223 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,614 | server.py:237 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2023-09-18 17:46:23,627 | server.py:125 | fit progress: (10, 0.4269851351965143, {'accuracy': 0.79}, 0.8639165999999996)
DEBUG flwr 2023-09-18 17:46:23,627 | server.py:173 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2023-09-18 17:46:23,652 | server.py:187 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2023-09-18 17:46:23,652 | server.py:147 | FL finished in 0.8893812000000008
INFO flwr 2023-09-18 17:46:23,653 | app.py:218 | app_fit: losses_distributed [(1, 0.41931438197692233), (2, 0.4131750712792079), (3, 0.41291346748669944), (4, 0.41515408598241355), (5, 0.41891135105064936), (6, 0.418687202675002), (7, 0.41868546094213216), (8, 0.418685667855399), (9, 0.41868563635008677), (10, 0.4186856320926121)]
INFO flwr 2023-09-18 17:46:23,653 | app.py:219 | app_fit: metrics_distributed_fit {}
INFO flwr 2023-09-18 17:46:23,653 | app.py:220 | app_fit: metrics_distributed {}
INFO flwr 2023-09-18 17:46:23,653 | app.py:221 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.42299553936553613), (2, 0.42318669485711913), (3, 0.4247167514939962), (4, 0.4247221972649737), (5, 0.4260933780833511), (6, 0.426980787211221), (7, 0.42698765587527715), (8, 0.42698456457471023), (9, 0.42698525143596916), (10, 0.4269851351965143)]
INFO flwr 2023-09-18 17:46:23,653 | app.py:222 | app_fit: metrics_centralized {'accuracy': [(0, 0.45), (1, 0.7933333333333333), (2, 0.7933333333333333), (3, 0.7866666666666666), (4, 0.7866666666666666), (5, 0.7933333333333333), (6, 0.79), (7, 0.79), (8, 0.79), (9, 0.79), (10, 0.79)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
>>>>>>>>>>>>> evaluating on server-side
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.99087117,  0.8814774 ,  0.90233103,  0.3799154 ,  0.20704765,
         0.04557808,  0.0636605 ,  0.10312782]]), array([0.03829657])]
[array([[-1.99087117,  0.8814774 ,  0.90233103,  0.3799154 ,  0.20704765,
         0.04557808,  0.0636605 ,  0.10312782]]), array([0.03829657])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.9364855 ,  0.87179171,  0.85516145,  0.41897063,  0.22848461,
         0.09167084,  0.02890813,  0.05715584]]), array([0.00990822])]
[array([[-1.9364855 ,  0.87179171,  0.85516145,  0.41897063,  0.22848461,
         0.09167084,  0.02890813,  0.05715584]]), array([0.00990822])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.94546151,  0.9011794 ,  0.87491162,  0.43563597,  0.18552206,
         0.0957581 ,  0.02947461,  0.02272318]]), array([0.0070663])]
[array([[-1.94546151,  0.9011794 ,  0.87491162,  0.43563597,  0.18552206,
         0.0957581 ,  0.02947461,  0.02272318]]), array([0.0070663])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.94526781,  0.90099214,  0.874886  ,  0.43547639,  0.18551406,
         0.09574411,  0.02936571,  0.02266428]]), array([0.00728359])]
[array([[-1.94526781,  0.90099214,  0.874886  ,  0.43547639,  0.18551406,
         0.09574411,  0.02936571,  0.02266428]]), array([0.00728359])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.89874954,  0.92861546,  0.8323847 ,  0.42373762,  0.19893409,
         0.07305304, -0.00310716,  0.0388665 ]]), array([0.01717827])]
[array([[-1.89874954,  0.92861546,  0.8323847 ,  0.42373762,  0.19893409,
         0.07305304, -0.00310716,  0.0388665 ]]), array([0.01717827])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.89445904,  0.92560559,  0.80092649,  0.4133223 ,  0.19334689,
         0.05527083, -0.01790084,  0.01577225]]), array([0.0723447])]
[array([[-1.89445904,  0.92560559,  0.80092649,  0.4133223 ,  0.19334689,
         0.05527083, -0.01790084,  0.01577225]]), array([0.0723447])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.89637277,  0.92646016,  0.80073819,  0.41356201,  0.19342444,
         0.05508975, -0.0181698 ,  0.01537646]]), array([0.07487611])]
[array([[-1.89637277,  0.92646016,  0.80073819,  0.41356201,  0.19342444,
         0.05508975, -0.0181698 ,  0.01537646]]), array([0.07487611])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.89620242,  0.9262942 ,  0.80075658,  0.41349173,  0.19335651,
         0.05512703, -0.01813953,  0.01543475]]), array([0.07465612])]
[array([[-1.89620242,  0.9262942 ,  0.80075658,  0.41349173,  0.19335651,
         0.05512703, -0.01813953,  0.01543475]]), array([0.07465612])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.89622964,  0.92632487,  0.80075272,  0.41350097,  0.19336892,
         0.05511688, -0.01814598,  0.01542583]]), array([0.07469491])]
[array([[-1.89622964,  0.92632487,  0.80075272,  0.41350097,  0.19336892,
         0.05511688, -0.01814598,  0.01542583]]), array([0.07469491])]
>>>>>>>>>>>>> evaluating on server-side
[array([[-1.89622516,  0.92631971,  0.80075339,  0.41349947,  0.19336678,
         0.05511849, -0.01814488,  0.01542728]]), array([0.07468847])]
[array([[-1.89622516,  0.92631971,  0.80075339,  0.41349947,  0.19336678,
         0.05511849, -0.01814488,  0.01542728]]), array([0.07468847])]
>>>>>>>>>>>>>run time:
0.515625s
