2024-07-11 12:55:35.708031: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2024-07-11 12:55:35.708217: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO flwr 2024-07-11 12:55:45,214 | app.py:165 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2024-07-11 12:55:45,297 | app.py:179 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2024-07-11 12:55:45,298 | server.py:89 | Initializing global parameters
INFO flwr 2024-07-11 12:55:45,298 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2024-07-11 12:55:46,883 | server.py:280 | Received initial parameters from one random client
INFO flwr 2024-07-11 12:55:46,884 | server.py:91 | Evaluating initial parameters
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:46,901 | server.py:98 | initial parameters (loss, other metrics): 0.6931471805599453, {'accuracy': 0.39}
INFO flwr 2024-07-11 12:55:46,901 | server.py:104 | FL starting
DEBUG flwr 2024-07-11 12:55:47,310 | server.py:227 | fit_round 1: strategy sampled 2 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:47,360 | server.py:241 | fit_round 1 received 2 results and 0 failures
WARNING flwr 2024-07-11 12:55:47,363 | fedavgm.py:198 | No fit_metrics_aggregation_fn provided
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:47,371 | server.py:131 | fit progress: (1, 0.40007778246520515, {'accuracy': 0.81}, 0.46938179999999896)
DEBUG flwr 2024-07-11 12:55:47,371 | server.py:178 | evaluate_round 1: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:47,401 | server.py:192 | evaluate_round 1 received 3 results and 0 failures
WARNING flwr 2024-07-11 12:55:47,401 | fedavg.py:273 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2024-07-11 12:55:47,401 | server.py:227 | fit_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:47,440 | server.py:241 | fit_round 2 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:47,450 | server.py:131 | fit progress: (2, 0.39993750518161214, {'accuracy': 0.8066666666666666}, 0.5496514000000001)
DEBUG flwr 2024-07-11 12:55:47,451 | server.py:178 | evaluate_round 2: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:47,479 | server.py:192 | evaluate_round 2 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:55:47,479 | server.py:227 | fit_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:47,508 | server.py:241 | fit_round 3 received 3 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:47,519 | server.py:131 | fit progress: (3, 0.3999322778731088, {'accuracy': 0.8066666666666666}, 0.6185709999999993)
DEBUG flwr 2024-07-11 12:55:47,520 | server.py:178 | evaluate_round 3: strategy sampled 3 clients (out of 3)
DEBUG flwr 2024-07-11 12:55:47,551 | server.py:192 | evaluate_round 3 received 3 results and 0 failures
DEBUG flwr 2024-07-11 12:55:47,551 | server.py:227 | fit_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:47,602 | server.py:241 | fit_round 4 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:47,613 | server.py:131 | fit progress: (4, 0.4002187751038839, {'accuracy': 0.8033333333333333}, 0.7112151000000004)
DEBUG flwr 2024-07-11 12:55:47,613 | server.py:178 | evaluate_round 4: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:47,635 | server.py:192 | evaluate_round 4 received 4 results and 0 failures
DEBUG flwr 2024-07-11 12:55:47,636 | server.py:227 | fit_round 5: strategy sampled 4 clients (out of 4)
DEBUG flwr 2024-07-11 12:55:47,674 | server.py:241 | fit_round 5 received 4 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:47,686 | server.py:131 | fit progress: (5, 0.40021315057398965, {'accuracy': 0.8033333333333333}, 0.7857480999999993)
DEBUG flwr 2024-07-11 12:55:47,687 | server.py:178 | evaluate_round 5: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:47,723 | server.py:192 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:47,723 | server.py:227 | fit_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:47,765 | server.py:241 | fit_round 6 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:47,777 | server.py:131 | fit progress: (6, 0.402288802677069, {'accuracy': 0.8}, 0.8763681999999999)
DEBUG flwr 2024-07-11 12:55:47,778 | server.py:178 | evaluate_round 6: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:47,817 | server.py:192 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:47,818 | server.py:227 | fit_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:47,867 | server.py:241 | fit_round 7 received 5 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:47,879 | server.py:131 | fit progress: (7, 0.402292133705013, {'accuracy': 0.8}, 0.9774562000000007)
DEBUG flwr 2024-07-11 12:55:47,879 | server.py:178 | evaluate_round 7: strategy sampled 5 clients (out of 5)
DEBUG flwr 2024-07-11 12:55:47,921 | server.py:192 | evaluate_round 7 received 5 results and 0 failures
DEBUG flwr 2024-07-11 12:55:47,921 | server.py:227 | fit_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:47,985 | server.py:241 | fit_round 8 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:47,997 | server.py:131 | fit progress: (8, 0.4025149750847417, {'accuracy': 0.7966666666666666}, 1.0962619999999994)
DEBUG flwr 2024-07-11 12:55:47,997 | server.py:178 | evaluate_round 8: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:48,040 | server.py:192 | evaluate_round 8 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:55:48,040 | server.py:227 | fit_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:48,099 | server.py:241 | fit_round 9 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:48,112 | server.py:131 | fit progress: (9, 0.40250794500643444, {'accuracy': 0.7966666666666666}, 1.2105648999999996)
DEBUG flwr 2024-07-11 12:55:48,112 | server.py:178 | evaluate_round 9: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:48,149 | server.py:192 | evaluate_round 9 received 6 results and 0 failures
DEBUG flwr 2024-07-11 12:55:48,150 | server.py:227 | fit_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:48,225 | server.py:241 | fit_round 10 received 6 results and 0 failures
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
D:\Anaconda3\envs\fl_py37\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
INFO flwr 2024-07-11 12:55:48,241 | server.py:131 | fit progress: (10, 0.40249941258103755, {'accuracy': 0.7966666666666666}, 1.3402364999999996)
DEBUG flwr 2024-07-11 12:55:48,242 | server.py:178 | evaluate_round 10: strategy sampled 6 clients (out of 6)
DEBUG flwr 2024-07-11 12:55:48,269 | server.py:192 | evaluate_round 10 received 6 results and 0 failures
INFO flwr 2024-07-11 12:55:48,270 | server.py:153 | FL finished in 1.3686095999999992
INFO flwr 2024-07-11 12:55:48,270 | app.py:225 | app_fit: losses_distributed [(1, 0.4101324323564768), (2, 0.408924899995327), (3, 0.40892408788204193), (4, 0.4156765470902125), (5, 0.40743410741460734), (6, 0.4063000709846102), (7, 0.4063002333558839), (8, 0.4083707434790475), (9, 0.4083717444113323), (10, 0.40837290287017824)]
INFO flwr 2024-07-11 12:55:48,270 | app.py:226 | app_fit: metrics_distributed_fit {}
INFO flwr 2024-07-11 12:55:48,270 | app.py:227 | app_fit: metrics_distributed {}
INFO flwr 2024-07-11 12:55:48,270 | app.py:228 | app_fit: losses_centralized [(0, 0.6931471805599453), (1, 0.40007778246520515), (2, 0.39993750518161214), (3, 0.3999322778731088), (4, 0.4002187751038839), (5, 0.40021315057398965), (6, 0.402288802677069), (7, 0.402292133705013), (8, 0.4025149750847417), (9, 0.40250794500643444), (10, 0.40249941258103755)]
INFO flwr 2024-07-11 12:55:48,271 | app.py:229 | app_fit: metrics_centralized {'accuracy': [(0, 0.39), (1, 0.81), (2, 0.8066666666666666), (3, 0.8066666666666666), (4, 0.8033333333333333), (5, 0.8033333333333333), (6, 0.8), (7, 0.8), (8, 0.7966666666666666), (9, 0.7966666666666666), (10, 0.7966666666666666)]}
>>>>>>>>>>>>> setting initial parameters
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]), array([0., 0.])]
[array([[-1.94319394,  0.94648037,  0.8427601 ,  0.55832132,  0.22802009,
         0.07758109,  0.09872332,  0.15753131]]), array([-0.43828661])]
[array([[-1.98110475,  0.945587  ,  0.78438792,  0.45620728,  0.27483045,
         0.10572091,  0.07145742,  0.16871705]]), array([-0.28034248])]
[array([[-1.98145087,  0.94562729,  0.78454844,  0.45610582,  0.27505312,
         0.10582516,  0.0714265 ,  0.16866673]]), array([-0.2807785])]
[array([[-1.92475395,  0.88717303,  0.82858126,  0.34250342,  0.18085718,
         0.08056848, -0.00547038,  0.10342958]]), array([0.0582143])]
[array([[-1.92546671,  0.88740035,  0.82888717,  0.34261798,  0.18044698,
         0.08034308, -0.00535188,  0.1032061 ]]), array([0.0593962])]
[array([[-2.04787099,  0.95266739,  0.8013385 ,  0.41322465,  0.1916104 ,
         0.08431649, -0.01720384,  0.03227466]]), array([0.15209575])]
[array([[-2.04753863,  0.95251783,  0.80101   ,  0.41306289,  0.19179842,
         0.08448463, -0.01725395,  0.03234838]]), array([0.1518704])]
[array([[-2.03241139,  0.96833647,  0.8134009 ,  0.41546381,  0.19408961,
         0.1145324 , -0.01924231,  0.04500091]]), array([0.03523123])]
[array([[-2.03147173,  0.96730908,  0.81309156,  0.41470347,  0.19359589,
         0.11432316, -0.01859481,  0.04465454]]), array([0.03573126])]
[array([[-2.03215426,  0.96737526,  0.81315   ,  0.41480291,  0.19370006,
         0.11456528, -0.01755588,  0.04425076]]), array([0.03598008])]
>>>>>>>>>>>>>run time:
0.671875s
